# CAFA5 STRING Interactions

This notebook processes STRING database protein-protein interaction (PPI) data and adds it to the CAFA5 reasoning dataset.

## Configuration

**Important**: Update the paths in the configuration cell below to match your local setup.

In [ ]:
# ============================================================================
# CONFIGURATION - Update these paths to match your local setup
# ============================================================================
import os

# Base directory for CAFA5 dataset (HuggingFace format)
CAFA5_BASE_DIR = os.path.join("data", "cafa5_reasoning")  # Update this path

# STRING database files directory
STRING_DATA_DIR = os.path.join("data", "string")  # Update this path

# Output directory for processed files
OUTPUT_DIR = os.path.join("data", "processed")  # Update this path

# Paths to STRING database files
UNIPROT_STRING_MAPPING = os.path.join(STRING_DATA_DIR, "all_organisms.uniprot_2_string.tsv")
STRING_PROTEIN_INFO = os.path.join(STRING_DATA_DIR, "protein.info.v12.0.txt")
STRING_PROTEIN_LINKS_PARQUET = os.path.join(STRING_DATA_DIR, "parquet_output_duckdb", "protein_links_space_delimited.parquet")

# Create output directory if it doesn't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Configuration loaded. Update paths above if needed.")

## Setup Instructions

For HPC/cluster environments, run the following commands on a compute node:

In [2]:
python -m venv $SLURM_TMPDIR/bioreason_env
module load python
module load gcc arrow
module load postgresql

source $SLURM_TMPDIR/bioreason_env/bin/activate
pip install --no-index notebook duckdb polars-u64-idx datasets
jupyter notebook --no-browser --ip=$(hostname -f) --port=8888

Downloads (from https://string-db.org/cgi/download)

https://stringdb-downloads.org/download/protein.links.detailed.v12.0.txt.gz

https://stringdb-downloads.org/download/protein.info.v12.0.txt.gz

# Initial Analysis

Load both splits of the cafa5 from storage

In [14]:
import os
import polars as pl

# base directory
base_dir = CAFA5_BASE_DIR

# file paths
train_fp = os.path.join(base_dir, "train-00000-of-00001.parquet")
test_fp  = os.path.join(base_dir, "test-00000-of-00001.parquet")

# read train & tag
train_pl = pl.read_parquet(train_fp).with_columns([
    pl.lit(True).alias("is_train")
])

# read test & tag
test_pl = pl.read_parquet(test_fp).with_columns([
    pl.lit(False).alias("is_train")
])

# concatenate into one DataFrame
cafa5_pl = pl.concat([train_pl, test_pl], how="vertical")

# sanity check
print(cafa5_pl.schema)
print(cafa5_pl.head(3))

Schema([('protein_id', String), ('protein_names', String), ('protein_function', String), ('organism', String), ('length', Float64), ('subcellular_location', String), ('sequence', String), ('go_ids', List(String)), ('go_bp', List(String)), ('go_mf', List(String)), ('go_cc', List(String)), ('interpro_ids', List(String)), ('structure_path', String), ('is_train', Boolean)])
shape: (3, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ go_cc     ┆ interpro_ ┆ structure ┆ is_train │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---       ┆ ids       ┆ _path     ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ bool     │
│ str       ┆ str       ┆ str       ┆           ┆   ┆           ┆ list[str] ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A087X1C ┆ Putative  ┆ May be    ┆ Homo      ┆ … ┆ ["GO:0005 ┆ ["IPR0011 ┆ AF-A0A087 ┆ true     │
│ 5         ┆ cytochrom ┆ responsib ┆ sapiens   ┆   ┆ 575", "GO ┆ 28", "IPR ┆ X1C5-F1-m ┆          │
│           ┆ e P450    ┆ le for    ┆ (Human)   ┆   ┆ :0110165" ┆ 017972",  ┆ odel_v4.c ┆          │
│           ┆ 2D7 (…    ┆ the met…  ┆           ┆   ┆ , ……      ┆ … "…      ┆ if        ┆          │
│ A0A0B4J2F ┆ Protein   ┆ Plays a   ┆ Homo      ┆ … ┆ ["GO:0005 ┆ null      ┆ AF-A0A0B4 ┆ true     │
│ 0         ┆ PIGBOS1   ┆ role in   ┆ sapiens   ┆   ┆ 575", "GO ┆           ┆ J2F0-F1-m ┆          │
│           ┆ (PIGB     ┆ regulatio ┆ (Human)   ┆   ┆ :0110165" ┆           ┆ odel_v4.c ┆          │
│           ┆ opposite… ┆ n of …    ┆           ┆   ┆ , ……      ┆           ┆ if        ┆          │
│ A0A0A7EPL ┆ E4 SUMO-p ┆ E4-type   ┆ Arabidops ┆ … ┆ null      ┆ ["IPR0041 ┆ AF-A0A0A7 ┆ true     │
│ 0         ┆ rotein    ┆ SUMO      ┆ is        ┆   ┆           ┆ 81", "IPR ┆ EPL0-F1-m ┆          │
│           ┆ ligase    ┆ ligase    ┆ thaliana  ┆   ┆           ┆ 013083"]  ┆ odel_v4.c ┆          │
│           ┆ PIAL1 (…  ┆ that      ┆ (Mouse-ea ┆   ┆           ┆           ┆ if        ┆          │
│           ┆           ┆ promo…    ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Load the uniprot to string conversion table (from string database)

In [20]:
# load uniprot to string data

import polars as pl

mapping_path = UNIPROT_STRING_MAPPING
cols = ["species", "uniprot_ac|uniprot_id", "string_id", "identity", "bit_score"]

# Load and clean, skipping the bad header
uniprot_string_map_df = pl.read_csv(
    mapping_path,
    separator="\t",
    comment_prefix="#",
    has_header=False,
    new_columns=cols,
    ignore_errors=True
)

# Split the combined column into accession and ID, then drop the original
uniprot_string_map_df = (
    uniprot_string_map_df
    .with_columns(
        pl.col("uniprot_ac|uniprot_id")
          .str.split_exact("|", 1)
          .struct
          .rename_fields(["uniprot_ac", "uniprot_id"])
          .alias("split")
    )
    .unnest("split")
    .drop("uniprot_ac|uniprot_id")
)

# Preview
# print(uniprot_string_map_df.head(5))

Reads the string/name table from raw text to polars

In [ ]:
import polars as pl

# --- Configuration fallback: only set if not already defined ---
if 'protein_info_path' not in globals():
    protein_info_path = STRING_PROTEIN_INFO

# Define the actual column names (strip the leading '#')
cols = ["string_protein_id", "preferred_name", "protein_size", "annotation"]

# --- Load the uncompressed protein.info file, using our header names ---
protein_info_df = pl.read_csv(
    protein_info_path,
    separator="\t",
    has_header=False,   # file's first line isn't a usable header
    skip_rows=1,        # skip the '#...' header line
    new_columns=cols    # apply our cleaned column names
)

# Preview columns & first few rows
print("Columns:", protein_info_df.columns)
print(protein_info_df.head(5))

Columns: ['string_protein_id', 'preferred_name', 'protein_size', 'annotation']
shape: (5, 4)
┌───────────────────┬────────────────┬──────────────┬─────────────────────────────────┐
│ string_protein_id ┆ preferred_name ┆ protein_size ┆ annotation                      │
│ ---               ┆ ---            ┆ ---          ┆ ---                             │
│ str               ┆ str            ┆ i64          ┆ str                             │
╞═══════════════════╪════════════════╪══════════════╪═════════════════════════════════╡
│ 23.BEL05_00025    ┆ BEL05_00025    ┆ 429          ┆ Hypothetical protein; Incomple… │
│ 23.BEL05_00030    ┆ OEG73659.1     ┆ 203          ┆ 2-keto-4-pentenoate hydratase;… │
│ 23.BEL05_00035    ┆ OEG73660.1     ┆ 1140         ┆ Hybrid sensor histidine kinase… │
│ 23.BEL05_00040    ┆ acsA           ┆ 650          ┆ acetate--CoA ligase; Catalyzes… │
│ 23.BEL05_00045    ┆ OEG73662.1     ┆ 579          ┆ ATP-dependent helicase; Derive… │
└───────────────────┴────────────────┴──────────────┴─────────────────────────────────┘

Brings the string ids into the cafa5 dataset, matching based on the uniprot id

In [21]:
# join uniprot cafa5 data with string id

import polars as pl

# 2) Prepare the mapping: only uniprot_ac → string_id
map_pl = uniprot_string_map_df.select(["uniprot_ac", "string_id"])

# 3) Join on protein_id ↔ uniprot_ac
joined = cafa5_pl.join(
    map_pl,
    left_on="protein_id",
    right_on="uniprot_ac",
    how="left"
)

cafa5_pl = joined.select(
    cafa5_pl.columns + ["string_id"]
)

# 5) Quick check
print(cafa5_pl.head(10))

shape: (10, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ interpro_ ┆ structure ┆ is_train ┆ string_id │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ids       ┆ _path     ┆ ---      ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ bool     ┆ str       │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ list[str] ┆ str       ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ A0A087X1C ┆ Putative  ┆ May be    ┆ Homo      ┆ … ┆ ["IPR0011 ┆ AF-A0A087 ┆ true     ┆ null      │
│ 5         ┆ cytochrom ┆ responsib ┆ sapiens   ┆   ┆ 28", "IPR ┆ X1C5-F1-m ┆          ┆           │
│           ┆ e P450    ┆ le for    ┆ (Human)   ┆   ┆ 017972",  ┆ odel_v4.c ┆          ┆           │
│           ┆ 2D7 (…    ┆ the met…  ┆           ┆   ┆ … "…      ┆ if        ┆          ┆           │
│ A0A0B4J2F ┆ Protein   ┆ Plays a   ┆ Homo      ┆ … ┆ null      ┆ AF-A0A0B4 ┆ true     ┆ 9606.ENSP │
│ 0         ┆ PIGBOS1   ┆ role in   ┆ sapiens   ┆   ┆           ┆ J2F0-F1-m ┆          ┆ 000004848 │
│           ┆ (PIGB     ┆ regulatio ┆ (Human)   ┆   ┆           ┆ odel_v4.c ┆          ┆ 93        │
│           ┆ opposite… ┆ n of …    ┆           ┆   ┆           ┆ if        ┆          ┆           │
│ A0A0A7EPL ┆ E4 SUMO-p ┆ E4-type   ┆ Arabidops ┆ … ┆ ["IPR0041 ┆ AF-A0A0A7 ┆ true     ┆ 3702.A0A0 │
│ 0         ┆ rotein    ┆ SUMO      ┆ is        ┆   ┆ 81", "IPR ┆ EPL0-F1-m ┆          ┆ A7EPL0    │
│           ┆ ligase    ┆ ligase    ┆ thaliana  ┆   ┆ 013083"]  ┆ odel_v4.c ┆          ┆           │
│           ┆ PIAL1 (…  ┆ that      ┆ (Mouse-ea ┆   ┆           ┆ if        ┆          ┆           │
│           ┆           ┆ promo…    ┆ …         ┆   ┆           ┆           ┆          ┆           │
│ A0A0B4J1G ┆ Low       ┆ Receptor  ┆ Mus       ┆ … ┆ ["IPR0071 ┆ AF-A0A0B4 ┆ true     ┆ 10090.ENS │
│ 0         ┆ affinity  ┆ for the   ┆ musculus  ┆   ┆ 10", "IPR ┆ J1G0-F1-m ┆          ┆ MUSP00000 │
│           ┆ immunoglo ┆ invariabl ┆ (Mouse)   ┆   ┆ 036179",  ┆ odel_v4.c ┆          ┆ 077873    │
│           ┆ bulin ga… ┆ e Fc…     ┆           ┆   ┆ … "…      ┆ if        ┆          ┆           │
│ A0A0B4J1N ┆ Protein   ┆ Highly    ┆ Mus       ┆ … ┆ ["IPR0317 ┆ AF-A0A0B4 ┆ true     ┆ 10090.ENS │
│ 3         ┆ GPR15LG   ┆ cationic  ┆ musculus  ┆   ┆ 13"]      ┆ J1N3-F1-m ┆          ┆ MUSP00000 │
│           ┆ (Protein  ┆ protein   ┆ (Mouse)   ┆   ┆           ┆ odel_v4.c ┆          ┆ 136426    │
│           ┆ GPR15…    ┆ that h…   ┆           ┆   ┆           ┆ if        ┆          ┆           │
│ A0A096MJY ┆ Myocyte-s ┆ Transcrip ┆ Rattus    ┆ … ┆ ["IPR0221 ┆ AF-A0A096 ┆ true     ┆ 10116.ENS │
│ 4         ┆ pecific   ┆ tion      ┆ norvegicu ┆   ┆ 02", "IPR ┆ MJY4-F1-m ┆          ┆ RNOP00000 │
│           ┆ enhancer  ┆ activator ┆ s (Rat)   ┆   ┆ 033896",  ┆ odel_v4.c ┆          ┆ 068323    │
│           ┆ fact…     ┆ which …   ┆           ┆   ┆ … "…      ┆ if        ┆          ┆           │
│ A0A0B4J1F ┆ Arrestin  ┆ Functions ┆ Mus       ┆ … ┆ ["IPR0147 ┆ AF-A0A0B4 ┆ true     ┆ 10090.ENS │
│ 4         ┆ domain-co ┆ as an     ┆ musculus  ┆   ┆ 52", "IPR ┆ J1F4-F1-m ┆          ┆ MUSP00000 │
│           ┆ ntaining  ┆ adapter   ┆ (Mouse)   ┆   ┆ 011021",  ┆ odel_v4.c ┆          ┆ 044578    │
│           ┆ pro…      ┆ recrui…   ┆           ┆   ┆ … "…      ┆ if        ┆          ┆           │
│ A0A0B4K7J ┆ E3 SUMO-p ┆ E3 SUMO-p ┆ Drosophil ┆ … ┆ ["IPR0119 ┆ null      ┆ true     ┆ 7227.FBpp │
│ 2         ┆ rotein    ┆ rotein    ┆ a melanog ┆   ┆ 93", "IPR ┆           ┆          ┆ 0293235   │
│           ┆ ligase    ┆ ligase    ┆ aster     ┆   ┆ 000156",  ┆           ┆          ┆           │
│           ┆ RanBP2 …  ┆ (By sim…  ┆ (Fruit…   ┆   ┆ … "…      ┆           ┆          ┆           │
│ A0A0B4KEE ┆ Klaroid   ┆ Component ┆ Drosophil ┆ … ┆ ["IPR0451 ┆ AF-A0A0B4 ┆ true     ┆ 7227.FBpp │
│ 4         ┆ protein   ┆ of the    ┆ a melanog ┆   ┆ 19", "IPR ┆ KEE4-F1-m ┆          ┆ 0307480   │
│           ┆           ┆ LINC      ┆ aster     ┆   ┆ 012919"]  ┆ odel_v4.c ┆          ┆           │
│           ┆           ┆ (LInker … ┆ (Fruit…   ┆   ┆           ┆ if        ┆          ┆           │
│ A0A088MLT ┆ IQCJ-SCHI ┆ May play  ┆ Mus       ┆ … ┆ ["IPR0293 ┆ AF-A0A088 ┆ true     ┆ 10090.ENS │
│ 8         ┆ P1 readth ┆ a role in ┆ musculus  ┆   ┆ 62", "IPR ┆ MLT8-F1-m ┆          ┆ MUSP00000 │
│           ┆ rough     ┆ action    ┆ (Mouse)   ┆   ┆ 039045",  ┆ odel_v4.c ┆          ┆ 138212    │
│           ┆ transc…   ┆ pote…     ┆           ┆   ┆ "IP…      ┆ if        ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

Convert the String data file from txt to a parquet file

In [4]:
# # This cell efficiently converts the STRING data file to a Parquet file using DuckDB.


# import duckdb
# import os

# # Paths
# input_path = os.path.join(STRING_DATA_DIR, 'protein.links.detailed.v12.0.txt.gz')
# output_dir = os.path.join(STRING_DATA_DIR, 'parquet_output_duckdb')
# output_path = os.path.join(output_dir, 'protein_links_space_delimited.parquet')

# # Ensure output directory exists
# os.makedirs(output_dir, exist_ok=True)

# print("Starting conversion with DuckDB... This will be much faster.")

# # Connect to DuckDB
# con = duckdb.connect()

# # Set the number of threads (cores) DuckDB should use
# # You can set this to the number of physical cores you have (12 in your case)
# # or even a bit higher if you have hyperthreading, but 12 is a good starting point.
# con.execute("SET threads = 12;") 

# # This single command streams the 25.8 billion rows from the gzipped CSV
# # and writes it to a single, efficient Parquet file.
# # DuckDB handles all the memory management and parallel processing.
# # Note: The original file is tab-separated ('\t'), so we specify that.
# # We also assume the first row is a header. If not, set header=False.
# con.execute(f"""
#     COPY (
#         SELECT *
#         FROM read_csv('{input_path}', header=True, delim=' ', compression='gzip')
#     ) TO '{output_path}' (FORMAT 'PARQUET', CODEC 'ZSTD');
# """)

# print(f"Successfully converted the entire file to {output_path}")

# # Close the connection
# con.close()

(8 min) Copy the STRING data to slurm tempdir for faster processing

In [ ]:
# --- Prep: parallel-copy parquet to local Slurm tempdir with progress bar ---
import os
import multiprocessing as mp

# make sure you have tqdm installed: pip install --user tqdm
from tqdm import tqdm

# --- Configuration ---
input_parquet_path = STRING_PROTEIN_LINKS_PARQUET

def _copy_chunk(src, dst, offset, size):
    with open(src, "rb") as fsrc, open(dst, "r+b") as fdst:
        fsrc.seek(offset)
        fdst.seek(offset)
        fdst.write(fsrc.read(size))

# Top-level worker so multiprocessing can pickle it
def _copy_worker(args):
    src, dst, offset, size = args
    _copy_chunk(src, dst, offset, size)
    return None

def parallel_copy_with_progress(src: str, dst: str, chunk_size: int = 512 * 1024 * 1024):
    total_size = os.path.getsize(src)
    # Pre-allocate destination file
    with open(dst, "wb") as f:
        f.truncate(total_size)

    # Build all chunk tasks
    tasks = [
        (src, dst, offset, min(chunk_size, total_size - offset))
        for offset in range(0, total_size, chunk_size)
    ]

    # Copy in parallel, wrapping the iterator in tqdm to see progress
    with mp.Pool(mp.cpu_count()) as pool:
        for _ in tqdm(
            pool.imap_unordered(_copy_worker, tasks),
            total=len(tasks),
            desc="Copying chunks",
            unit="chunk"
        ):
            pass

# Determine Slurm temp directory and target path
slurm_tmpdir = os.environ.get("SLURM_TMPDIR", "/tmp")
local_parquet_path = os.path.join(slurm_tmpdir, os.path.basename(input_parquet_path))

print(f"Starting parallel copy to:\n  {local_parquet_path}\n(512 MB per chunk, {mp.cpu_count()} cores)…")
parallel_copy_with_progress(input_parquet_path, local_parquet_path)

# Reassign so downstream code reads from the local copy
input_parquet_path = local_parquet_path
print("Done. Now reading from local path:", input_parquet_path)

Copying
  /scratch/naimerja/BioReason2/PPI/Data/STRING_Full_Data/parquet_output_duckdb/protein_links_space_delimited.parquet
to
  /localscratch/naimerja.45617684.0/protein_links_space_delimited.parquet

Filter string data to only include rows with confidence >70% and which are related to a cafa5 protein

Takes ~15 minutues with 64 cpus and slow SLURM disk performance, for faster performance copy protein_links_space_delimited.parquet to SLURM_TEMPDIR with above cell

In [ ]:
import polars as pl

if 'input_parquet_path' not in globals():
    input_parquet_path = STRING_PROTEIN_LINKS_PARQUET

# Configuration: use all threads and a suitable streaming chunk size
pl.Config.set_streaming_chunk_size(1_000_000)  # Optional: tune chunk size for streaming

MIN_COMBINED_SCORE = 700

# Build CAFA5 ID list (assuming cafa5_pl is a Polars DataFrame already in memory)
string_ids = cafa5_pl["string_id"].drop_nulls().unique().to_list()
print(f"CAFA5 filter will use {len(string_ids)} unique string IDs")

# Lazy scan with optimized parallelism
lf = pl.scan_parquet(
    input_parquet_path,
    parallel="row_groups",   # parallelize over row groups to utilize all cores
    use_statistics=True      # enable Parquet page skipping by stats
    # low_memory=False is default (we prefer performance),
    # rechunk=False is default (avoid extra copying before collect)
)

# Apply filters lazily
lf = lf.filter(pl.col("combined_score") >= MIN_COMBINED_SCORE)
lf = lf.filter(pl.col("protein1").is_in(string_ids))

# Collect results with streaming (to pipeline reading & filtering)
print("Executing query in streaming mode...")
final_df = lf.collect(engine="streaming")  # or engine="streaming" on newer Polars

print("Done! Final dataframe has shape", final_df.shape)

CAFA5 filter will use 99821 unique string IDs
Executing query in streaming mode...
Done! Final dataframe has shape (2770689, 10)

In [13]:
final_df.head(10)

shape: (10, 10)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ protein1   ┆ protein2   ┆ neighborho ┆ fusion ┆ … ┆ experimen ┆ database ┆ textminin ┆ combined_ │
│ ---        ┆ ---        ┆ od         ┆ ---    ┆   ┆ tal       ┆ ---      ┆ g         ┆ score     │
│ str        ┆ str        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ i64      ┆ ---       ┆ ---       │
│            ┆            ┆ i64        ┆        ┆   ┆ i64       ┆          ┆ i64       ┆ i64       │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 52.CMC5_04 ┆ 52.CMC5_05 ┆ 105        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 223       ┆ 955       │
│ 7490       ┆ 2310       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_04 ┆ 718        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 718       │
│ 7490       ┆ 7480       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_08 ┆ 91         ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 157       ┆ 794       │
│ 7490       ┆ 4210       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_00 ┆ 105        ┆ 163    ┆ … ┆ 0         ┆ 0        ┆ 223       ┆ 961       │
│ 7490       ┆ 2690       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_05 ┆ 91         ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 157       ┆ 794       │
│ 7490       ┆ 8910       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_02 ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 770       │
│ 7500       ┆ 5350       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_07 ┆ 87         ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 762       │
│ 7500       ┆ 4250       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_03 ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 69        ┆ 741       │
│ 7500       ┆ 2580       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_02 ┆ 325        ┆ 0      ┆ … ┆ 188       ┆ 0        ┆ 354       ┆ 851       │
│ 7510       ┆ 3720       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_01 ┆ 188        ┆ 0      ┆ … ┆ 865       ┆ 0        ┆ 110       ┆ 925       │
│ 7510       ┆ 0050       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [14]:
print("Estimated in-memory size:", final_df.estimated_size() / 1e6, "MB")

Estimated in-memory size: 394.270205 MB

Writes the filtered string dataframe to disk

In [15]:
output_path = os.path.join(OUTPUT_DIR, "filtered_protein_links.parquet")
final_df.write_parquet(output_path, compression="zstd")

Reads the filtered string dataframe

In [10]:
import polars as pl

# Path to the saved file
output_path = os.path.join(OUTPUT_DIR, "filtered_protein_links.parquet")

# Read the file
filtered_df = pl.read_parquet(output_path)

# Show shape and head
print("Shape:", filtered_df.shape)
print(filtered_df.tail())

Shape: (4044631, 10)
shape: (5, 10)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ protein1   ┆ protein2   ┆ neighborho ┆ fusion ┆ … ┆ experimen ┆ database ┆ textminin ┆ combined_ │
│ ---        ┆ ---        ┆ od         ┆ ---    ┆   ┆ tal       ┆ ---      ┆ g         ┆ score     │
│ str        ┆ str        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ i64      ┆ ---       ┆ ---       │
│            ┆            ┆ i64        ┆        ┆   ┆ i64       ┆          ┆ i64       ┆ i64       │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 830       ┆ 445      ┆ 50        ┆ 908       │
│ K19_21110  ┆ K19_09730  ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 831       ┆ 445      ┆ 0         ┆ 929       │
│ K19_21110  ┆ K19_13875  ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 67         ┆ 0      ┆ … ┆ 831       ┆ 412      ┆ 0         ┆ 903       │
│ K19_21110  ┆ K19_17125  ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 697       ┆ 410      ┆ 185       ┆ 873       │
│ K19_21110  ┆ K19_10375  ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 59         ┆ 0      ┆ … ┆ 224       ┆ 573      ┆ 199       ┆ 775       │
│ K19_21110  ┆ K19_05790  ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴──────────┴───────────┴───────────┘

replace protein2 string code with protein2 name

In [11]:
import polars as pl

# --- Replace protein2 IDs with their preferred names ---
# 1. Rename original protein2 to protein2_string
filtered_df = filtered_df.rename({"protein2": "protein2_string"})

# 2. Join to bring in the preferred_name from protein_info_df
filtered_df = filtered_df.join(
    protein_info_df.select(["string_protein_id", "preferred_name"]),
    left_on="protein2_string",
    right_on="string_protein_id",
    how="left"
)

# 3. Overwrite protein2 with the joined preferred_name
filtered_df = filtered_df.with_columns(
    pl.col("preferred_name").alias("protein2")
)

# 4. Drop any helper columns that were added
to_drop = [c for c in ["string_protein_id", "preferred_name"] if c in filtered_df.columns]
filtered_df = filtered_df.drop(to_drop)

# Now filtered_df.protein2 contains the preferred names,
# and the original IDs are in filtered_df.protein2_string.

In [12]:
filtered_df

shape: (4_044_631, 11)
┌────────────┬────────────┬────────────┬────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ protein1   ┆ protein2_s ┆ neighborho ┆ fusion ┆ … ┆ database ┆ textminin ┆ combined_ ┆ protein2  │
│ ---        ┆ tring      ┆ od         ┆ ---    ┆   ┆ ---      ┆ g         ┆ score     ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ i64    ┆   ┆ i64      ┆ ---       ┆ ---       ┆ str       │
│            ┆ str        ┆ i64        ┆        ┆   ┆          ┆ i64       ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 52.CMC5_04 ┆ 52.CMC5_05 ┆ 105        ┆ 0      ┆ … ┆ 0        ┆ 223       ┆ 955       ┆ hutI      │
│ 7490       ┆ 2310       ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_04 ┆ 718        ┆ 0      ┆ … ┆ 0        ┆ 0         ┆ 718       ┆ AKT40592. │
│ 7490       ┆ 7480       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 52.CMC5_04 ┆ 52.CMC5_08 ┆ 91         ┆ 0      ┆ … ┆ 0        ┆ 157       ┆ 794       ┆ AKT44181. │
│ 7490       ┆ 4210       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 52.CMC5_04 ┆ 52.CMC5_00 ┆ 105        ┆ 163    ┆ … ┆ 0        ┆ 223       ┆ 961       ┆ hutU      │
│ 7490       ┆ 2690       ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 52.CMC5_04 ┆ 52.CMC5_05 ┆ 91         ┆ 0      ┆ … ┆ 0        ┆ 157       ┆ 794       ┆ AKT41685. │
│ 7490       ┆ 8910       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 445      ┆ 50        ┆ 908       ┆ rps24e    │
│ K19_21110  ┆ K19_09730  ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 445      ┆ 0         ┆ 929       ┆ rps4e     │
│ K19_21110  ┆ K19_13875  ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 67         ┆ 0      ┆ … ┆ 412      ┆ 0         ┆ 903       ┆ rps13     │
│ K19_21110  ┆ K19_17125  ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 0          ┆ 0      ┆ … ┆ 410      ┆ 185       ┆ 873       ┆ psmB      │
│ K19_21110  ┆ K19_10375  ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1803814.AY ┆ 1803814.AY ┆ 59         ┆ 0      ┆ … ┆ 573      ┆ 199       ┆ 775       ┆ eif2b     │
│ K19_21110  ┆ K19_05790  ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [15]:
print("CAFA5 column types:")
print(cafa5_pl.schema)

print("\nFiltered DF column types:")
print(filtered_df.schema)

CAFA5 column types:
Schema([('protein_id', String), ('protein_names', String), ('protein_function', String), ('organism', String), ('length', Float64), ('subcellular_location', String), ('sequence', String), ('go_ids', List(String)), ('go_bp', List(String)), ('go_mf', List(String)), ('go_cc', List(String)), ('interpro_ids', List(String)), ('structure_path', String), ('is_train', Boolean)])

Filtered DF column types:
Schema([('protein1', String), ('protein2_string', String), ('neighborhood', Int64), ('fusion', Int64), ('cooccurence', Int64), ('coexpression', Int64), ('experimental', Int64), ('database', Int64), ('textmining', Int64), ('combined_score', Int64), ('protein2', String)])

Groups filtered string df by protein 1 and then adds column with all associated protein 2 and another with all proteins 2 along with individual scores

In [13]:
import polars as pl

grouped_df = (
    filtered_df
    .group_by("protein1")
    .agg([
        # 1. List of all protein2 values per protein1
        pl.col("protein2").implode().alias("interaction_partners"),

        # 2. Struct of full interaction info, collected into list
        pl.struct([
            pl.col("protein2"),
            pl.col("neighborhood"),
            pl.col("fusion"),
            pl.col("cooccurence"),
            pl.col("coexpression"),
            pl.col("experimental"),
            pl.col("database"),
            pl.col("textmining"),
            pl.col("combined_score"),
        ]).implode().alias("full_interaction_info"),
    ])
)

print("Grouped shape:", grouped_df.shape)
print(grouped_df.head())

Grouped shape: (134653, 3)
shape: (5, 3)
┌──────────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ protein1                 ┆ interaction_partners            ┆ full_interaction_info           │
│ ---                      ┆ ---                             ┆ ---                             │
│ str                      ┆ list[str]                       ┆ list[struct[9]]                 │
╞══════════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 284592.Q6BLV6            ┆ ["Q6BWV8_DEBHA", "Q6BRD8_DEBHA… ┆ [{"Q6BWV8_DEBHA",0,0,0,0,0,900… │
│ 9606.ENSP00000380872     ┆ ["CD3G", "CD3E"]                ┆ [{"CD3G",0,0,0,833,0,0,157,852… │
│ 284812.P0CG72            ┆ ["ubc15", "set1", … "rps1502"]  ┆ [{"ubc15",0,0,0,54,975,0,212,9… │
│ 10090.ENSMUSP00000023869 ┆ ["Rack1", "Eif3b", … "Ebna1bp2… ┆ [{"Rack1",0,0,0,86,766,0,142,8… │
│ 284812.Q09704            ┆ ["rcl1", "utp20", … "utp24"]    ┆ [{"rcl1",0,0,0,175,553,400,0,7… │
└──────────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [16]:
cafa5_pl

shape: (275_360, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ go_cc     ┆ interpro_ ┆ structure ┆ is_train │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---       ┆ ids       ┆ _path     ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ bool     │
│ str       ┆ str       ┆ str       ┆           ┆   ┆           ┆ list[str] ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0A087X1C ┆ Putative  ┆ May be    ┆ Homo      ┆ … ┆ ["GO:0005 ┆ ["IPR0011 ┆ AF-A0A087 ┆ true     │
│ 5         ┆ cytochrom ┆ responsib ┆ sapiens   ┆   ┆ 575", "GO ┆ 28", "IPR ┆ X1C5-F1-m ┆          │
│           ┆ e P450    ┆ le for    ┆ (Human)   ┆   ┆ :0110165" ┆ 017972",  ┆ odel_v4.c ┆          │
│           ┆ 2D7 (…    ┆ the met…  ┆           ┆   ┆ , ……      ┆ … "…      ┆ if        ┆          │
│ A0A0B4J2F ┆ Protein   ┆ Plays a   ┆ Homo      ┆ … ┆ ["GO:0005 ┆ null      ┆ AF-A0A0B4 ┆ true     │
│ 0         ┆ PIGBOS1   ┆ role in   ┆ sapiens   ┆   ┆ 575", "GO ┆           ┆ J2F0-F1-m ┆          │
│           ┆ (PIGB     ┆ regulatio ┆ (Human)   ┆   ┆ :0110165" ┆           ┆ odel_v4.c ┆          │
│           ┆ opposite… ┆ n of …    ┆           ┆   ┆ , ……      ┆           ┆ if        ┆          │
│ A0A0A7EPL ┆ E4 SUMO-p ┆ E4-type   ┆ Arabidops ┆ … ┆ null      ┆ ["IPR0041 ┆ AF-A0A0A7 ┆ true     │
│ 0         ┆ rotein    ┆ SUMO      ┆ is        ┆   ┆           ┆ 81", "IPR ┆ EPL0-F1-m ┆          │
│           ┆ ligase    ┆ ligase    ┆ thaliana  ┆   ┆           ┆ 013083"]  ┆ odel_v4.c ┆          │
│           ┆ PIAL1 (…  ┆ that      ┆ (Mouse-ea ┆   ┆           ┆           ┆ if        ┆          │
│           ┆           ┆ promo…    ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ A0A0B4J1G ┆ Low       ┆ Receptor  ┆ Mus       ┆ … ┆ ["GO:0005 ┆ ["IPR0071 ┆ AF-A0A0B4 ┆ true     │
│ 0         ┆ affinity  ┆ for the   ┆ musculus  ┆   ┆ 575", "GO ┆ 10", "IPR ┆ J1G0-F1-m ┆          │
│           ┆ immunoglo ┆ invariabl ┆ (Mouse)   ┆   ┆ :0110165" ┆ 036179",  ┆ odel_v4.c ┆          │
│           ┆ bulin ga… ┆ e Fc…     ┆           ┆   ┆ , ……      ┆ … "…      ┆ if        ┆          │
│ A0A0B4J1N ┆ Protein   ┆ Highly    ┆ Mus       ┆ … ┆ null      ┆ ["IPR0317 ┆ AF-A0A0B4 ┆ true     │
│ 3         ┆ GPR15LG   ┆ cationic  ┆ musculus  ┆   ┆           ┆ 13"]      ┆ J1N3-F1-m ┆          │
│           ┆ (Protein  ┆ protein   ┆ (Mouse)   ┆   ┆           ┆           ┆ odel_v4.c ┆          │
│           ┆ GPR15…    ┆ that h…   ┆           ┆   ┆           ┆           ┆ if        ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Q4A3R3    ┆ null      ┆ May play  ┆ Sus       ┆ … ┆ ["None"]  ┆ ["IPR0008 ┆ AF-Q4A3R3 ┆ false    │
│           ┆           ┆ roles in  ┆ scrofa    ┆   ┆           ┆ 59", "IPR ┆ -F1-model ┆          │
│           ┆           ┆ mucosal   ┆           ┆   ┆           ┆ 035914",  ┆ _v4.cif   ┆          │
│           ┆           ┆ defe…     ┆           ┆   ┆           ┆ … "…      ┆           ┆          │
│ Q5E9L2    ┆ null      ┆ Inhibits  ┆ Bos       ┆ … ┆ ["None"]  ┆ ["IPR0332 ┆ AF-Q5E9L2 ┆ false    │
│           ┆           ┆ cell prol ┆ taurus    ┆   ┆           ┆ 37", "IPR ┆ -F1-model ┆          │
│           ┆           ┆ iferation ┆ (cattle)  ┆   ┆           ┆ 020864"]  ┆ _v4.cif   ┆          │
│           ┆           ┆ by…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q3T0K9    ┆ null      ┆ In unstre ┆ Bos       ┆ … ┆ ["None"]  ┆ ["IPR0227 ┆ AF-Q3T0K9 ┆ false    │
│           ┆           ┆ ssed      ┆ taurus    ┆   ┆           ┆ 30"]      ┆ -F1-model ┆          │
│           ┆           ┆ cells,    ┆ (cattle)  ┆   ┆           ┆           ┆ _v4.cif   ┆          │
│           ┆           ┆ promotes  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q58CX7    ┆ null      ┆ null      ┆ Bos       ┆ … ┆ ["None"]  ┆ ["IPR0205 ┆ AF-Q58CX7 ┆ false    │
│           ┆           ┆           ┆ taurus    ┆   ┆           ┆ 19", "IPR ┆ -F1-model ┆          │
│           ┆           ┆           ┆ (cattle)  ┆   ┆           ┆ 022049"]  ┆ _v4.cif   ┆          │
│ A7E300    ┆ null      ┆ Functions ┆ Bos       ┆ … ┆ ["None"]  ┆ ["IPR0089 ┆ AF-A7E300 ┆ false    │
│           ┆           ┆ as a GTPa ┆ taurus    ┆   ┆           ┆ 36", "IPR ┆ -F1-model ┆          │
│           ┆           ┆ se-activa ┆ (cattle)  ┆   ┆           ┆ 000198",  ┆ _v4.cif   ┆          │
│           ┆           ┆ ti…       ┆           ┆   ┆           ┆ … "…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Connects the PPI data with the cafa5 data

In [22]:
merged_df = cafa5_pl.join(
    grouped_df,
    left_on="string_id",
    right_on="protein1",
    how="left"
)

# Only drop 'protein1' if it exists (e.g., when join didn't auto-drop it)
if "protein1" in merged_df.columns:
    merged_df = merged_df.drop("protein1")

print("Merged shape:", merged_df.shape)
print(merged_df.select(["string_id", "interaction_partners", "full_interaction_info"]).head())

Merged shape: (275402, 17)
shape: (5, 3)
┌──────────────────────────┬────────────────────────────────┬─────────────────────────────────┐
│ string_id                ┆ interaction_partners           ┆ full_interaction_info           │
│ ---                      ┆ ---                            ┆ ---                             │
│ str                      ┆ list[str]                      ┆ list[struct[9]]                 │
╞══════════════════════════╪════════════════════════════════╪═════════════════════════════════╡
│ null                     ┆ null                           ┆ null                            │
│ 9606.ENSP00000484893     ┆ null                           ┆ null                            │
│ 3702.A0A0A7EPL0          ┆ ["ESD4", "SUMO1", … "SAE1B-1"] ┆ [{"ESD4",0,0,0,0,107,0,811,823… │
│ 10090.ENSMUSP00000077873 ┆ ["Gm5150", "Vav1", … "Cd3g"]   ┆ [{"Gm5150",0,0,0,139,414,0,490… │
│ 10090.ENSMUSP00000136426 ┆ ["Gpr15"]                      ┆ [{"Gpr15",0,0,0,0,0,0,792,792}… │
└──────────────────────────┴────────────────────────────────┴─────────────────────────────────┘

In [23]:
# The percentage of rows in cafa5 WITHOUT an entry in string->uniprot table
sum(merged_df['string_id'].is_null())

44140

In [31]:
# The percent of rows in cafa5 WITHOUT interaction partners
sum(merged_df['interaction_partners'].is_null())/len(merged_df)*100

27.20786341420905

Saves the cafa5 data with the 2 new PPI columns to disk

In [25]:
output_path = os.path.join(OUTPUT_DIR, "cafa5_merged_with_interactions.parquet")

merged_df.write_parquet(output_path, compression="zstd")

In [1]:
import polars as pl

# Path to the saved file
merged_path = os.path.join(OUTPUT_DIR, "cafa5_merged_with_interactions.parquet")

# Read the merged DataFrame
merged_df = pl.read_parquet(merged_path)

# Preview shape and a few rows
print("Shape:", merged_df.shape)
merged_df.sample(9)

Shape: (275402, 17)

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ is_train ┆ string_id ┆ interacti ┆ full_inte │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---      ┆ ---       ┆ on_partne ┆ raction_i │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ bool     ┆ str       ┆ rs        ┆ nfo       │
│ str       ┆ str       ┆ str       ┆           ┆   ┆          ┆           ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆ list[stru │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ct[9]]    │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ Q7ZU74    ┆ Insulin   ┆ null      ┆ Danio     ┆ … ┆ true     ┆ null      ┆ null      ┆ null      │
│           ┆ receptor  ┆           ┆ rerio (Ze ┆   ┆          ┆           ┆           ┆           │
│           ┆ substrate ┆           ┆ brafish)  ┆   ┆          ┆           ┆           ┆           │
│           ┆ 2a …      ┆           ┆ (Brach…   ┆   ┆          ┆           ┆           ┆           │
│ P06634    ┆ ATP-depen ┆ ATP-bindi ┆ Saccharom ┆ … ┆ false    ┆ 4932.YOR2 ┆ ["PSP2",  ┆ [{"PSP2", │
│           ┆ dent RNA  ┆ ng RNA    ┆ yces cere ┆   ┆          ┆ 04W       ┆ "ATP16",  ┆ 0,0,0,94, │
│           ┆ helicase  ┆ helicase  ┆ visiae    ┆   ┆          ┆           ┆ … "NOC3"] ┆ 817,0,69, │
│           ┆ DED…      ┆ invol…    ┆ (stra…    ┆   ┆          ┆           ┆           ┆ 832…      │
│ P9WFF7    ┆ Decapreny ┆ Catalyzes ┆ Mycobacte ┆ … ┆ true     ┆ 83332.Rv2 ┆ ["idsA1", ┆ [{"idsA1" │
│           ┆ l diphosp ┆ the seque ┆ rium tube ┆   ┆          ┆ 361c      ┆ "idsB", … ┆ ,71,0,622 │
│           ┆ hate      ┆ ntial     ┆ rculosis  ┆   ┆          ┆           ┆ "grcC1"]  ┆ ,91,0,0,6 │
│           ┆ synthas…  ┆ conde…    ┆ (st…      ┆   ┆          ┆           ┆           ┆ 69,…      │
│ Q24151    ┆ Signal    ┆ Might     ┆ Drosophil ┆ … ┆ false    ┆ 7227.FBpp ┆ ["Su(var) ┆ [{"Su(var │
│           ┆ transduce ┆ play a    ┆ a melanog ┆   ┆          ┆ 0306651   ┆ 205",     ┆ )205",0,0 │
│           ┆ r and     ┆ role in   ┆ aster     ┆   ┆          ┆           ┆ "dpp", …  ┆ ,0,47,517 │
│           ┆ transcri… ┆ signal    ┆ (Fruit…   ┆   ┆          ┆           ┆ "Ptp61…   ┆ ,0,…      │
│           ┆           ┆ tr…       ┆           ┆   ┆          ┆           ┆           ┆           │
│ Q9M1G6    ┆ Basic     ┆ Transcrip ┆ Arabidops ┆ … ┆ false    ┆ 3702.Q9M1 ┆ ["ABI3",  ┆ [{"ABI3", │
│           ┆ leucine   ┆ tion      ┆ is        ┆   ┆          ┆ G6        ┆ "BZIP2",  ┆ 0,0,0,0,2 │
│           ┆ zipper 25 ┆ factor    ┆ thaliana  ┆   ┆          ┆           ┆ … "F1O13. ┆ 30,0,956, │
│           ┆ (AtbZI…   ┆ that      ┆ (Mouse-ea ┆   ┆          ┆           ┆ 3"]       ┆ 964…      │
│           ┆           ┆ bind…     ┆ …         ┆   ┆          ┆           ┆           ┆           │
│ P06399    ┆ Fibrinoge ┆ Cleaved   ┆ Rattus    ┆ … ┆ false    ┆ 10116.ENS ┆ ["Mbl1",  ┆ [{"Mbl1", │
│           ┆ n alpha   ┆ by the    ┆ norvegicu ┆   ┆          ┆ RNOP00000 ┆ "Ambp", … ┆ 0,0,0,750 │
│           ┆ chain     ┆ protease  ┆ s (Rat)   ┆   ┆          ┆ 060007    ┆ "Ahsg"]   ┆ ,0,0,111, │
│           ┆ [Cleave…  ┆ thromb…   ┆           ┆   ┆          ┆           ┆           ┆ 768…      │
│ A0A494C0Q ┆ Poly(A)-s ┆ null      ┆ Homo      ┆ … ┆ true     ┆ null      ┆ null      ┆ null      │
│ 6         ┆ pecific   ┆           ┆ sapiens   ┆   ┆          ┆           ┆           ┆           │
│           ┆ ribonucle ┆           ┆ (Human)   ┆   ┆          ┆           ┆           ┆           │
│           ┆ ase …     ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Q385H8    ┆ Uncharact ┆ null      ┆ Trypanoso ┆ … ┆ true     ┆ 185431.Q3 ┆ null      ┆ null      │
│           ┆ erized    ┆           ┆ ma brucei ┆   ┆          ┆ 85H8      ┆           ┆           │
│           ┆ protein   ┆           ┆ brucei    ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ (str…     ┆   ┆          ┆           ┆           ┆           │
│ Q9WVC7    ┆ A-kinase  ┆ Binds to  ┆ Rattus    ┆ … ┆ true     ┆ 10116.ENS ┆ ["Akap1", ┆ [{"Akap1" │
│           ┆ anchor    ┆ type II   ┆ norvegicu ┆   ┆          ┆ RNOP00000 ┆ "Pde4d",  ┆ ,0,0,0,64 │
│           ┆ protein 6 ┆ regulator ┆ s (Rat)   ┆   ┆          ┆ 006562    ┆ …         ┆ ,0,0,754, │
│           ┆ (AKA…     ┆ y su…     ┆           ┆   ┆          ┆           ┆ "Akap9"]  ┆ 760…      │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [2]:
merged_df.sample(10)

shape: (10, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ is_train ┆ string_id ┆ interacti ┆ full_inte │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---      ┆ ---       ┆ on_partne ┆ raction_i │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ bool     ┆ str       ┆ rs        ┆ nfo       │
│ str       ┆ str       ┆ str       ┆           ┆   ┆          ┆           ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ list[str] ┆ list[stru │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ct[9]]    │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ Q10295    ┆ Poly(A)   ┆ Polymeras ┆ Schizosac ┆ … ┆ false    ┆ 284812.Q1 ┆ ["rna15", ┆ [{"rna15" │
│           ┆ polymeras ┆ e that    ┆ charomyce ┆   ┆          ┆ 0295      ┆ "iss1", … ┆ ,0,0,0,0, │
│           ┆ e pla1    ┆ creates   ┆ s pombe   ┆   ┆          ┆           ┆ "gtr2"]   ┆ 745,900,8 │
│           ┆ (PAP) …   ┆ the 3'…   ┆ (str…     ┆   ┆          ┆           ┆           ┆ 81,…      │
│ A0PGB2    ┆ Telomeras ┆ Component ┆ Tetrahyme ┆ … ┆ true     ┆ null      ┆ null      ┆ null      │
│           ┆ e-associa ┆ of a      ┆ na thermo ┆   ┆          ┆           ┆           ┆           │
│           ┆ ted       ┆ CST-like  ┆ phila     ┆   ┆          ┆           ┆           ┆           │
│           ┆ protein … ┆ subcom…   ┆ (strai…   ┆   ┆          ┆           ┆           ┆           │
│ Q814X0    ┆ NADH-quin ┆ NDH-1     ┆ Bacillus  ┆ … ┆ false    ┆ 226900.BC ┆ ["nuoA",  ┆ [{"nuoA", │
│           ┆ one oxido ┆ shuttles  ┆ cereus    ┆   ┆          ┆ _5297     ┆ "BC_2838" ┆ 805,0,774 │
│           ┆ reductase ┆ electrons ┆ (strain   ┆   ┆          ┆           ┆ , …       ┆ ,908,871, │
│           ┆ su…       ┆ from …    ┆ ATCC 1…   ┆   ┆          ┆           ┆ "BC_2022… ┆ 976…      │
│ Q9NZC9    ┆ SWI/SNF-r ┆ ATP-depen ┆ Homo      ┆ … ┆ false    ┆ 9606.ENSP ┆ ["MUS81", ┆ [{"MUS81" │
│           ┆ elated    ┆ dent      ┆ sapiens   ┆   ┆          ┆ 000003498 ┆ "RECQL5", ┆ ,0,0,0,31 │
│           ┆ matrix-as ┆ annealing ┆ (Human)   ┆   ┆          ┆ 23        ┆ … "RPA1"] ┆ 4,136,0,7 │
│           ┆ socia…    ┆ helica…   ┆           ┆   ┆          ┆           ┆           ┆ 39,…      │
│ Q9T072    ┆ Transcrip ┆ null      ┆ Arabidops ┆ … ┆ false    ┆ 3702.Q9T0 ┆ ["F13M23. ┆ [{"F13M23 │
│           ┆ tion      ┆           ┆ is        ┆   ┆          ┆ 72        ┆ 290"]     ┆ .290",0,0 │
│           ┆ factor    ┆           ┆ thaliana  ┆   ┆          ┆           ┆           ┆ ,0,0,0,0, │
│           ┆ bHLH25    ┆           ┆ (Mouse-ea ┆   ┆          ┆           ┆           ┆ 759…      │
│           ┆ (B…       ┆           ┆ …         ┆   ┆          ┆           ┆           ┆           │
│ Q86NP2    ┆ Negative  ┆ Essential ┆ Drosophil ┆ … ┆ true     ┆ 7227.FBpp ┆ ["ear",   ┆ [{"ear",0 │
│           ┆ elongatio ┆ component ┆ a melanog ┆   ┆          ┆ 0303402   ┆ "NELF-B", ┆ ,0,0,0,0, │
│           ┆ n factor  ┆ of the    ┆ aster     ┆   ┆          ┆           ┆ … "Spt5"] ┆ 720,0,720 │
│           ┆ A         ┆ NEL…      ┆ (Fruit…   ┆   ┆          ┆           ┆           ┆ }, …      │
│ Q9C110    ┆ Meiotical ┆ Has a     ┆ Schizosac ┆ … ┆ true     ┆ 284812.Q9 ┆ null      ┆ null      │
│           ┆ ly up-reg ┆ role in   ┆ charomyce ┆   ┆          ┆ C110      ┆           ┆           │
│           ┆ ulated    ┆ meiosis.  ┆ s pombe   ┆   ┆          ┆           ┆           ┆           │
│           ┆ gene …    ┆           ┆ (str…     ┆   ┆          ┆           ┆           ┆           │
│ P63142    ┆ Potassium ┆ Voltage-g ┆ Rattus    ┆ … ┆ false    ┆ 10116.ENS ┆ ["Kcna6", ┆ [{"Kcna6" │
│           ┆ voltage-g ┆ ated      ┆ norvegicu ┆   ┆          ┆ RNOP00000 ┆ "Kcnab2", ┆ ,0,0,58,6 │
│           ┆ ated      ┆ potassium ┆ s (Rat)   ┆   ┆          ┆ 075852    ┆ …         ┆ 4,133,400 │
│           ┆ channe…   ┆ channe…   ┆           ┆   ┆          ┆           ┆ "LOC6877… ┆ ,84…      │
│ Q9BSJ5    ┆ Mitochond ┆ null      ┆ Homo      ┆ … ┆ false    ┆ 9606.ENSP ┆ ["H7C0C1_ ┆ [{"H7C0C1 │
│           ┆ rial nucl ┆           ┆ sapiens   ┆   ┆          ┆ 000003519 ┆ HUMAN",   ┆ _HUMAN",0 │
│           ┆ eoid-asso ┆           ┆ (Human)   ┆   ┆          ┆ 37        ┆ "ATP5PD", ┆ ,0,0,371, │
│           ┆ cia…      ┆           ┆           ┆   ┆          ┆           ┆ … "…      ┆ 750…      │
│ Q5ZKW2    ┆ Protein   ┆ null      ┆ Gallus    ┆ … ┆ false    ┆ 9031.ENSG ┆ ["NAPG",  ┆ [{"NAPG", │
│           ┆ LZIC      ┆           ┆ gallus    ┆   ┆          ┆ ALP000000 ┆ "EPHA6",  ┆ 0,0,0,0,0 │
│           ┆ (Leucine  ┆           ┆ (Chicken) ┆   ┆          ┆ 04109     ┆ "NSUN3"]  ┆ ,0,849,84 │
│           ┆ zipper a… ┆           ┆           ┆   ┆          ┆           ┆           ┆ 9},…      │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [3]:
from datasets import Dataset

# If merged_df is a Polars DataFrame:
train_pd = (
    merged_df
    .filter(pl.col("is_train") == True)
    .drop("is_train")
    .to_pandas()
)
test_pd = (
    merged_df
    .filter(pl.col("is_train") == False)
    .drop("is_train")
    .to_pandas()
)

train_hf = Dataset.from_pandas(train_pd, preserve_index=False)
test_hf  = Dataset.from_pandas(test_pd,  preserve_index=False)

In [6]:
train_hf

Dataset({
    features: ['protein_id', 'protein_names', 'protein_function', 'organism', 'length', 'subcellular_location', 'sequence', 'go_ids', 'go_bp', 'go_mf', 'go_cc', 'interpro_ids', 'structure_path', 'string_id', 'interaction_partners', 'full_interaction_info'],
    num_rows: 133538
})

In [7]:
from datasets import DatasetDict
import os

# --- Paths ---
base_hf_dir = "/scratch/naimerja/BioReason2/PPI/Data/HuggingFace"
# Save under the “cafa5_reasoning” folder so it parallels the existing structure
save_dir = os.path.join(base_hf_dir, "cafa5_reasoning")

# Ensure the directory exists
os.makedirs(save_dir, exist_ok=True)

# --- Combine and save ---
cafa5_ds = DatasetDict({
    "train": train_hf,
    "test":  test_hf,
})

cafa5_ds.save_to_disk(save_dir)

print(f"Hugging Face splits saved to: {save_dir}")

Saving the dataset (0/2 shards):   0%|          | 0/133538 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/141864 [00:00<?, ? examples/s]

Hugging Face splits saved to: /scratch/naimerja/BioReason2/PPI/Data/HuggingFace/cafa5_reasoning