# SwissProt STRING Interactions

This notebook processes STRING database protein-protein interaction (PPI) data and adds it to the SwissProt reasoning dataset.

## Configuration

**Important**: Update the paths in the configuration cell below to match your local setup.

In [ ]:
# ============================================================================
# CONFIGURATION - Update these paths to match your local setup
# ============================================================================
import os

# Base directory for SwissProt dataset
SWISSPROT_DATA_DIR = os.path.join("data", "swissprot")  # Update this path

# STRING database files directory
STRING_DATA_DIR = os.path.join("data", "string")  # Update this path

# Output directory for processed files
OUTPUT_DIR = os.path.join("data", "processed")  # Update this path

# Paths to STRING database files
UNIPROT_STRING_MAPPING = os.path.join(STRING_DATA_DIR, "all_organisms.uniprot_2_string.tsv")
STRING_PROTEIN_INFO = os.path.join(STRING_DATA_DIR, "protein.info.v12.0.txt")
STRING_PROTEIN_LINKS_PARQUET = os.path.join(STRING_DATA_DIR, "parquet_output_duckdb", "protein_links_space_delimited.parquet")
STRING_PROTEIN_LINKS_GZ = os.path.join(STRING_DATA_DIR, "protein.links.detailed.v12.0.txt.gz")

# Create output directory if it doesn't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Configuration loaded. Update paths above if needed.")

Run the following on compute node

In [2]:
python -m venv $SLURM_TMPDIR/bioreason_env
module load python
module load gcc arrow
module load postgresql

source $SLURM_TMPDIR/bioreason_env/bin/activate
pip install --no-index notebook duckdb polars-u64-idx datasets
jupyter notebook --no-browser --ip=$(hostname -f) --port=8888

Downloads (from https://string-db.org/cgi/download)

https://stringdb-downloads.org/download/protein.links.detailed.v12.0.txt.gz

https://stringdb-downloads.org/download/protein.info.v12.0.txt.gz

# Initial Analysis

In [1]:
from datasets import load_dataset

# Load the train split
train_dataset = load_dataset(
    "wanglab/cafa5",
    data_files="swissprot_reasoning/train-*.parquet",
    split="train"
)

# Load the test split
test_dataset = load_dataset(
    "wanglab/cafa5",
    data_files="swissprot_reasoning/test-*.parquet",
    split="train"
)

print(train_dataset)
print(test_dataset)

Dataset({
    features: ['protein_id', 'protein_names', 'protein_function', 'organism', 'length', 'subcellular_location', 'sequence', 'go_ids', 'go_bp', 'go_mf', 'go_cc', 'structure_path', 'interpro_ids', 'interpro_location'],
    num_rows: 333677
})
Dataset({
    features: ['protein_id', 'protein_names', 'protein_function', 'organism', 'length', 'subcellular_location', 'sequence', 'go_ids', 'go_bp', 'go_mf', 'go_cc', 'structure_path', 'interpro_ids', 'interpro_location'],
    num_rows: 83420
})

Load both splits of the cafa5 from storage

In [2]:
# Convert HuggingFace Datasets to Polars DataFrames
import pandas as pd
import polars as pl

# Convert train and test datasets to pandas DataFrames, then to polars
train_df = train_dataset.to_pandas()
test_df = test_dataset.to_pandas()

train_pl = pl.from_pandas(train_df)
test_pl = pl.from_pandas(test_df)

# concatenate into one DataFrame
swissprot_pl = pl.concat([train_pl, test_pl], how="vertical")

# sanity check
print(swissprot_pl.schema)
print(swissprot_pl.head(3))

Schema([('protein_id', String), ('protein_names', String), ('protein_function', String), ('organism', String), ('length', Int64), ('subcellular_location', String), ('sequence', String), ('go_ids', List(String)), ('go_bp', List(String)), ('go_mf', List(String)), ('go_cc', List(String)), ('structure_path', String), ('interpro_ids', List(String)), ('interpro_location', String)])
shape: (3, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ go_cc     ┆ structure ┆ interpro_ ┆ interpro │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---       ┆ _path     ┆ ids       ┆ _locatio │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ n        │
│ str       ┆ str       ┆ str       ┆           ┆   ┆           ┆ str       ┆ list[str] ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q8CX00    ┆ Chaperoni ┆ Together  ┆ Streptoco ┆ … ┆ ["GO:0005 ┆ AF-Q8CX00 ┆ ["IPR0183 ┆ {"IPR027 │
│           ┆ n GroEL   ┆ with its  ┆ ccus agal ┆   ┆ 575", "GO ┆ -F1-model ┆ 70", "IPR ┆ 413":    │
│           ┆           ┆ co-chaper ┆ actiae    ┆   ┆ :0110165" ┆ _v4.cif   ┆ 001844",  ┆ [5,      │
│           ┆           ┆ oni…      ┆ serot…    ┆   ┆ , "…      ┆           ┆ … "…      ┆ 519],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR02…  │
│ Q4P9K9    ┆ Chitin    ┆ Polymeriz ┆ Ustilago  ┆ … ┆ ["GO:0005 ┆ AF-Q4P9K9 ┆ ["IPR0016 ┆ {"IPR027 │
│           ┆ synthase  ┆ es        ┆ maydis    ┆   ┆ 575", "GO ┆ -F1-model ┆ 09", "IPR ┆ 417":    │
│           ┆ 8         ┆ chitin, a ┆ (strain   ┆   ┆ :0110165" ┆ _v4.cif   ┆ 004835",  ┆ [5,      │
│           ┆           ┆ structur… ┆ 521 / …   ┆   ┆ , ……      ┆           ┆ … "…      ┆ 771],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR03…  │
│ A9WUW1    ┆ ATP-depen ┆ ATP-depen ┆ Renibacte ┆ … ┆ null      ┆ AF-A9WUW1 ┆ ["IPR0500 ┆ {"IPR038 │
│           ┆ dent Clp  ┆ dent spec ┆ rium salm ┆   ┆           ┆ -F1-model ┆ 52", "IPR ┆ 366":    │
│           ┆ protease  ┆ ificity   ┆ oninarum  ┆   ┆           ┆ _v4.cif   ┆ 038366",  ┆ [3, 50], │
│           ┆ ATP…      ┆ comp…     ┆ (st…      ┆   ┆           ┆           ┆ … "…      ┆ "IPR027… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
test_pl

shape: (83_420, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ go_cc     ┆ structure ┆ interpro_ ┆ interpro │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ ---       ┆ _path     ┆ ids       ┆ _locatio │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ n        │
│ str       ┆ str       ┆ str       ┆           ┆   ┆           ┆ str       ┆ list[str] ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ B2IUL7    ┆ Light-ind ┆ Component ┆ Nostoc    ┆ … ┆ null      ┆ AF-B2IUL7 ┆ ["IPR0059 ┆ {"IPR027 │
│           ┆ ependent  ┆ of the    ┆ punctifor ┆   ┆           ┆ -F1-model ┆ 71", "IPR ┆ 417":    │
│           ┆ protochlo ┆ dark-oper ┆ me        ┆   ┆           ┆ _v4.cif   ┆ 030655",  ┆ [1,      │
│           ┆ rop…      ┆ ativ…     ┆ (strain   ┆   ┆           ┆           ┆ … "…      ┆ 268],    │
│           ┆           ┆           ┆ ATC…      ┆   ┆           ┆           ┆           ┆ "IPR00…  │
│ Q1RJY6    ┆ Formamido ┆ Involved  ┆ Rickettsi ┆ … ┆ null      ┆ AF-Q1RJY6 ┆ ["IPR0158 ┆ {"IPR035 │
│           ┆ pyrimidin ┆ in base   ┆ a bellii  ┆   ┆           ┆ -F1-model ┆ 87", "IPR ┆ 937":    │
│           ┆ e-DNA     ┆ excision  ┆ (strain   ┆   ┆           ┆ _v4.cif   ┆ 020629",  ┆ [1,      │
│           ┆ glycos…   ┆ repa…     ┆ RML3…     ┆   ┆           ┆           ┆ … "…      ┆ 141],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR01…  │
│ P31614    ┆ Hemagglut ┆ Structura ┆ Murine    ┆ … ┆ ["GO:0005 ┆ null      ┆ ["IPR0425 ┆ {"IPR008 │
│           ┆ inin-este ┆ l protein ┆ coronavir ┆   ┆ 575", "GO ┆           ┆ 45", "IPR ┆ 980":    │
│           ┆ rase      ┆ that      ┆ us        ┆   ┆ :0110165" ┆           ┆ 003860",  ┆ [145,    │
│           ┆           ┆ makes …   ┆ (strain   ┆   ┆ , ……      ┆           ┆ … "…      ┆ 294],    │
│           ┆           ┆           ┆ S)        ┆   ┆           ┆           ┆           ┆ "IPR…    │
│ Q92FZ5    ┆ Transcrip ┆ Necessary ┆ Rickettsi ┆ … ┆ null      ┆ AF-Q92FZ5 ┆ ["IPR0181 ┆ {"IPR036 │
│           ┆ tion elon ┆ for       ┆ a conorii ┆   ┆           ┆ -F1-model ┆ 51", "IPR ┆ 805":    │
│           ┆ gation    ┆ efficient ┆ (strain   ┆   ┆           ┆ _v4.cif   ┆ 036953",  ┆ [1, 78], │
│           ┆ facto…    ┆ RNA po…   ┆ ATC…      ┆   ┆           ┆           ┆ … "…      ┆ "IPR036… │
│ Q8UE43    ┆ Dihydroxy ┆ Functions ┆ Agrobacte ┆ … ┆ null      ┆ AF-Q8UE43 ┆ ["IPR0005 ┆ {"IPR037 │
│           ┆ -acid deh ┆ in the    ┆ rium      ┆   ┆           ┆ -F1-model ┆ 81", "IPR ┆ 237":    │
│           ┆ ydratase  ┆ biosynthe ┆ fabrum    ┆   ┆           ┆ _v4.cif   ┆ 056740",  ┆ [4,      │
│           ┆           ┆ sis …     ┆ (strain   ┆   ┆           ┆           ┆ … "…      ┆ 420],    │
│           ┆           ┆           ┆ C…        ┆   ┆           ┆           ┆           ┆ "IPR04…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Q0C5R4    ┆ 3-phospho ┆ Catalyzes ┆ Hyphomona ┆ … ┆ ["GO:0005 ┆ AF-Q0C5R4 ┆ ["IPR0137 ┆ {"IPR013 │
│           ┆ shikimate ┆ the       ┆ s         ┆   ┆ 575", "GO ┆ -F1-model ┆ 92", "IPR ┆ 792":    │
│           ┆ 1-carboxy ┆ transfer  ┆ neptunium ┆   ┆ :0110165" ┆ _v4.cif   ┆ 006264",  ┆ [5,      │
│           ┆ vi…       ┆ of the …  ┆ (strain   ┆   ┆ , "…      ┆           ┆ … "…      ┆ 436],    │
│           ┆           ┆           ┆ A…        ┆   ┆           ┆           ┆           ┆ "IPR03…  │
│ P0A6S8    ┆ Glycerol- ┆ null      ┆ Escherich ┆ … ┆ ["GO:0005 ┆ AF-P0A6S8 ┆ ["IPR0362 ┆ {"IPR036 │
│           ┆ 3-phospha ┆           ┆ ia coli   ┆   ┆ 575", "GO ┆ -F1-model ┆ 91", "IPR ┆ 291":    │
│           ┆ te dehydr ┆           ┆ O6:H1     ┆   ┆ :0032991" ┆ _v4.cif   ┆ 013328",  ┆ [8,      │
│           ┆ oge…      ┆           ┆ (strain…  ┆   ┆ , ……      ┆           ┆ … "…      ┆ 182],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR00…  │
│ B7NN18    ┆ Periplasm ┆ Catalytic ┆ Escherich ┆ … ┆ ["GO:0005 ┆ AF-B7NN18 ┆ ["IPR0066 ┆ {"IPR009 │
│           ┆ ic        ┆ subunit   ┆ ia coli   ┆   ┆ 575", "GO ┆ -F1-model ┆ 56", "IPR ┆ 010":    │
│           ┆ nitrate   ┆ of the    ┆ O7:K1     ┆   ┆ :0032991" ┆ _v4.cif   ┆ 006657",  ┆ [688,    │
│           ┆ reductase ┆ perip…    ┆ (strain…  ┆   ┆ , ……      ┆           ┆ … "…      ┆ 828],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR…    │
│ A9KE87    ┆ tRNA-spec ┆ Catalyzes ┆ Coxiella  ┆ … ┆ ["GO:0005 ┆ AF-A9KE87 ┆ ["IPR0468 ┆ {"IPR014 │
│           ┆ ific 2-th ┆ the 2-thi ┆ burnetii  ┆   ┆ 575", "GO ┆ -F1-model ┆ 85", "IPR ┆ 729":    │
│           ┆ iouridyla ┆ olation   ┆ (strain   ┆   ┆ :0110165" ┆ _v4.cif   ┆ 014729",  ┆ [1,      │
│           ┆ se …      ┆ of …      ┆ Dugw…     ┆   ┆ , "…      ┆           ┆ … "…      ┆ 213],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR02…  │
│ Q9TDN0    ┆ Cytochrom ┆ Component ┆ Peponocep ┆ … ┆ ["GO:0005 ┆ AF-Q9TDN0 ┆ ["IPR0161 ┆ {"IPR016 │
│           ┆ e b       ┆ of the    ┆ hala      ┆   ┆ 575", "GO ┆ -F1-model ┆ 74", "IPR ┆ 174":    │
│           ┆           ┆ ubiquinol ┆ electra   ┆   ┆ :0110165" ┆ _v4.cif   ┆ 005797",  ┆ [1,      │
│           ┆           ┆ -cyt…     ┆           ┆   ┆ , ……      ┆           ┆ … "…      ┆ 260],    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "IPR02…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Load the uniprot to string conversion table (from string database)

In [3]:
# load uniprot to string data

import polars as pl

mapping_path = UNIPROT_STRING_MAPPING
cols = ["species", "uniprot_ac|uniprot_id", "string_id", "identity", "bit_score"]

# Load and clean, skipping the bad header
uniprot_string_map_df = pl.read_csv(
    mapping_path,
    separator="\t",
    comment_prefix="#",
    has_header=False,
    new_columns=cols,
    ignore_errors=True
)

# Split the combined column into accession and ID, then drop the original
uniprot_string_map_df = (
    uniprot_string_map_df
    .with_columns(
        pl.col("uniprot_ac|uniprot_id")
          .str.split_exact("|", 1)
          .struct
          .rename_fields(["uniprot_ac", "uniprot_id"])
          .alias("split")
    )
    .unnest("split")
    .drop("uniprot_ac|uniprot_id")
)

# Preview
# print(uniprot_string_map_df.head(5))

Reads the string/name table from raw text to polars

In [4]:
import polars as pl

# --- Configuration fallback: only set if not already defined ---
if 'protein_info_path' not in globals():
    protein_info_path = STRING_PROTEIN_INFO

# Define the actual column names (strip the leading '#')
cols = ["string_protein_id", "preferred_name", "protein_size", "annotation"]

# --- Load the uncompressed protein.info file, using our header names ---
protein_info_df = pl.read_csv(
    protein_info_path,
    separator="\t",
    has_header=False,   # file's first line isn't a usable header
    skip_rows=1,        # skip the '#...' header line
    new_columns=cols,    # apply our cleaned column names
    ignore_errors=True,
)

# Preview columns & first few rows
print("Columns:", protein_info_df.columns)
print(protein_info_df.head(5))

Columns: ['string_protein_id', 'preferred_name', 'protein_size', 'annotation']
shape: (5, 4)
┌───────────────────┬────────────────┬──────────────┬─────────────────────────────────┐
│ string_protein_id ┆ preferred_name ┆ protein_size ┆ annotation                      │
│ ---               ┆ ---            ┆ ---          ┆ ---                             │
│ str               ┆ str            ┆ i64          ┆ str                             │
╞═══════════════════╪════════════════╪══════════════╪═════════════════════════════════╡
│ 23.BEL05_00025    ┆ BEL05_00025    ┆ 429          ┆ Hypothetical protein; Incomple… │
│ 23.BEL05_00030    ┆ OEG73659.1     ┆ 203          ┆ 2-keto-4-pentenoate hydratase;… │
│ 23.BEL05_00035    ┆ OEG73660.1     ┆ 1140         ┆ Hybrid sensor histidine kinase… │
│ 23.BEL05_00040    ┆ acsA           ┆ 650          ┆ acetate--CoA ligase; Catalyzes… │
│ 23.BEL05_00045    ┆ OEG73662.1     ┆ 579          ┆ ATP-dependent helicase; Derive… │
└───────────────────┴────────────────┴──────────────┴─────────────────────────────────┘

sys:1: UserWarning: CSV malformed: expected 1 rows, actual 54947921 rows, in chunk starting at byte offset 402138335, length 6031279343

In [5]:
protein_info_df.shape

(59309604, 4)

Brings the string ids into the cafa5 dataset, matching based on the uniprot id

In [6]:
# join uniprot cafa5 data with string id

import polars as pl

# 2) Prepare the mapping: only uniprot_ac → string_id
map_pl = uniprot_string_map_df.select(["uniprot_ac", "string_id"])

# 3) Join on protein_id ↔ uniprot_ac
joined = swissprot_pl.join(
    map_pl,
    left_on="protein_id",
    right_on="uniprot_ac",
    how="left"
)

swissprot_pl = joined.select(
    swissprot_pl.columns + ["string_id"]
)

# 5) Quick check
print(swissprot_pl.head(10))

shape: (10, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ structure ┆ interpro_ ┆ interpro_ ┆ string_i │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ _path     ┆ ids       ┆ location  ┆ d        │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ list[str] ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q8CX00    ┆ Chaperoni ┆ Together  ┆ Streptoco ┆ … ┆ AF-Q8CX00 ┆ ["IPR0183 ┆ {"IPR0274 ┆ 208435.S │
│           ┆ n GroEL   ┆ with its  ┆ ccus agal ┆   ┆ -F1-model ┆ 70", "IPR ┆ 13": [5,  ┆ AG2074   │
│           ┆           ┆ co-chaper ┆ actiae    ┆   ┆ _v4.cif   ┆ 001844",  ┆ 519],     ┆          │
│           ┆           ┆ oni…      ┆ serot…    ┆   ┆           ┆ … "…      ┆ "IPR02…   ┆          │
│ Q4P9K9    ┆ Chitin    ┆ Polymeriz ┆ Ustilago  ┆ … ┆ AF-Q4P9K9 ┆ ["IPR0016 ┆ {"IPR0274 ┆ 237631.Q │
│           ┆ synthase  ┆ es        ┆ maydis    ┆   ┆ -F1-model ┆ 09", "IPR ┆ 17": [5,  ┆ 4P9K9    │
│           ┆ 8         ┆ chitin, a ┆ (strain   ┆   ┆ _v4.cif   ┆ 004835",  ┆ 771],     ┆          │
│           ┆           ┆ structur… ┆ 521 / …   ┆   ┆           ┆ … "…      ┆ "IPR03…   ┆          │
│ A9WUW1    ┆ ATP-depen ┆ ATP-depen ┆ Renibacte ┆ … ┆ AF-A9WUW1 ┆ ["IPR0500 ┆ {"IPR0383 ┆ 288705.R │
│           ┆ dent Clp  ┆ dent spec ┆ rium salm ┆   ┆ -F1-model ┆ 52", "IPR ┆ 66": [3,  ┆ Sal33209 │
│           ┆ protease  ┆ ificity   ┆ oninarum  ┆   ┆ _v4.cif   ┆ 038366",  ┆ 50],      ┆ _3266    │
│           ┆ ATP…      ┆ comp…     ┆ (st…      ┆   ┆           ┆ … "…      ┆ "IPR027…  ┆          │
│ A0A411KZU ┆ Burnettra ┆ Part of   ┆ Aspergill ┆ … ┆ AF-A0A411 ┆ ["IPR0532 ┆ {"IPR0532 ┆ null     │
│ 9         ┆ mic acids ┆ the gene  ┆ us        ┆   ┆ KZU9-F1-m ┆ 21"]      ┆ 21": [2,  ┆          │
│           ┆ biosynthe ┆ cluster   ┆ burnettii ┆   ┆ odel_v4.c ┆           ┆ 363]}     ┆          │
│           ┆ si…       ┆ that …    ┆           ┆   ┆ if        ┆           ┆           ┆          │
│ Q0AE59    ┆ 50S       ┆ null      ┆ Nitrosomo ┆ … ┆ AF-Q0AE59 ┆ ["IPR0209 ┆ {"IPR0002 ┆ 335283.N │
│           ┆ ribosomal ┆           ┆ nas       ┆   ┆ -F1-model ┆ 39", "IPR ┆ 71": [1,  ┆ eut_2151 │
│           ┆ protein   ┆           ┆ eutropha  ┆   ┆ _v4.cif   ┆ 000271"]  ┆ 44],      ┆          │
│           ┆ L34       ┆           ┆ (strain … ┆   ┆           ┆           ┆ "IPR020…  ┆          │
│ A5E891    ┆ Deoxyurid ┆ This      ┆ Bradyrhiz ┆ … ┆ AF-A5E891 ┆ ["IPR0361 ┆ {"IPR0361 ┆ 288000.B │
│           ┆ ine 5'-tr ┆ enzyme is ┆ obium sp. ┆   ┆ -F1-model ┆ 57", "IPR ┆ 57": [4,  ┆ Bta_0084 │
│           ┆ iphosphat ┆ involved  ┆ (strain   ┆   ┆ _v4.cif   ┆ 008181",  ┆ 152],     ┆          │
│           ┆ e n…      ┆ in nuc…   ┆ BTA…      ┆   ┆           ┆ … "…      ┆ "IPR00…   ┆          │
│ B7M340    ┆ Flagellar ┆ Functions ┆ Escherich ┆ … ┆ AF-B7M340 ┆ ["IPR0235 ┆ {"IPR0361 ┆ null     │
│           ┆ transcrip ┆ in        ┆ ia coli   ┆   ┆ -F1-model ┆ 59", "IPR ┆ 94": [4,  ┆          │
│           ┆ tional    ┆ complex   ┆ O8        ┆   ┆ _v4.cif   ┆ 036194"]  ┆ 119],     ┆          │
│           ┆ regu…     ┆ with      ┆ (strain   ┆   ┆           ┆           ┆ "IPR02…   ┆          │
│           ┆           ┆ FlhC…     ┆ IA…       ┆   ┆           ┆           ┆           ┆          │
│ A4TN08    ┆ 3-deoxy-m ┆ Activates ┆ Yersinia  ┆ … ┆ AF-A4TN08 ┆ ["IPR0033 ┆ {"IPR0290 ┆ null     │
│           ┆ anno-octu ┆ KDO (a    ┆ pestis    ┆   ┆ -F1-model ┆ 29", "IPR ┆ 44": [1,  ┆          │
│           ┆ losonate  ┆ required  ┆ (strain   ┆   ┆ _v4.cif   ┆ 004528",  ┆ 250],     ┆          │
│           ┆ cyt…      ┆ 8-ca…     ┆ Pestoi…   ┆   ┆           ┆ "IP…      ┆ "IPR00…   ┆          │
│ A4W094    ┆ Ornithine ┆ Reversibl ┆ Streptoco ┆ … ┆ AF-A4W094 ┆ ["IPR0061 ┆ {"IPR0369 ┆ null     │
│           ┆ carbamoyl ┆ y         ┆ ccus suis ┆   ┆ -F1-model ┆ 32", "IPR ┆ 01": [5,  ┆          │
│           ┆ transfera ┆ catalyzes ┆ (strain   ┆   ┆ _v4.cif   ┆ 006130",  ┆ 331],     ┆          │
│           ┆ se        ┆ the       ┆ 98H…      ┆   ┆           ┆ … "…      ┆ "IPR02…   ┆          │
│           ┆           ┆ trans…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ O77819    ┆ Rho-assoc ┆ Protein   ┆ Oryctolag ┆ … ┆ AF-O77819 ┆ ["IPR0575 ┆ {"IPR0110 ┆ 9986.ENS │
│           ┆ iated     ┆ kinase    ┆ us        ┆   ┆ -F1-model ┆ 29", "IPR ┆ 09": [73, ┆ OCUP0000 │
│           ┆ protein   ┆ which is  ┆ cuniculus ┆   ┆ _v4.cif   ┆ 000961",  ┆ 413],     ┆ 0034408  │
│           ┆ kinase …  ┆ a key …   ┆           ┆   ┆           ┆ … "…      ┆ "IPR0…    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Convert the String data file from txt to a parquet file

In [ ]:
# # This cell efficiently converts the STRING data file to a Parquet file using DuckDB.
# # MEMORY OPTIMIZED VERSION for large files (190GB+) on systems with limited RAM

# import duckdb
# import os
# import psutil

# # Paths
# input_path = '<path_to_string_data>/protein.links.detailed.v12.0.txt.gz'
# output_dir = '<path_to_string_data>/parquet_output_duckdb'
# output_path = os.path.join(output_dir, 'protein_links_space_delimited.parquet')

# # Ensure output directory exists
# os.makedirs(output_dir, exist_ok=True)

# # Check available memory and disk space
# available_memory_gb = psutil.virtual_memory().available / (1024**3)
# file_size_gb = os.path.getsize(input_path) / (1024**3)
# print(f"File size: {file_size_gb:.1f} GB")
# print(f"Available memory: {available_memory_gb:.1f} GB")

# print("Starting memory-optimized conversion with DuckDB...")

# # MEMORY OPTIMIZATION SETTINGS
# # Limit memory usage to ~60% of available RAM to leave room for OS and other processes
# max_memory_gb = max(1, int(available_memory_gb * 0.6))
# print(f"Setting DuckDB memory limit to {max_memory_gb} GB")

# # Reduce thread count for memory-constrained environments
# thread_count = min(8, os.cpu_count())  # Use fewer threads to reduce memory pressure
# print(f"Using {thread_count} threads")

# # Connect to DuckDB with optimized configuration
# # Using a temporary database file allows DuckDB to spill to disk when needed
# temp_db_path = os.path.join(output_dir, 'temp_conversion.duckdb')
# config = {
#     'memory_limit': f'{max_memory_gb}GB',
#     'threads': thread_count,
#     'temp_directory': '/tmp',
#     'preserve_insertion_order': False,
#     'enable_external_access': True
# }

# con = duckdb.connect(temp_db_path, config=config)

# try:
    
#     # Process the file with memory-efficient settings
#     print("Converting file (this may take longer but uses less memory)...")
#     con.execute(f"""
#         COPY (
#             SELECT *
#             FROM read_csv(
#                 '{input_path}', 
#                 header=True, 
#                 delim=' ', 
#                 compression='gzip',
#                 sample_size=100000  -- Smaller sample for schema detection to save memory
#             )
#         ) TO '{output_path}' (
#             FORMAT 'PARQUET', 
#             CODEC 'ZSTD',
#             ROW_GROUP_SIZE 100000  -- Smaller row groups for better memory management
#         );
#     """)
    
#     print(f"Successfully converted the entire file to {output_path}")
    
# finally:
#     # Close the connection and clean up temporary database
#     con.close()
#     if os.path.exists(temp_db_path):
#         os.remove(temp_db_path)
#         print("Cleaned up temporary database file")

File size: 189.6 GB
Available memory: 120.1 GB
Starting memory-optimized conversion with DuckDB...
Setting DuckDB memory limit to 72 GB
Using 8 threads
Converting file (this may take longer but uses less memory)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Successfully converted the entire file to <path_to_string_data>/parquet_output_duckdb/protein_links_space_delimited.parquet
Cleaned up temporary database file

In [2]:
# SYSTEM REQUIREMENTS CHECK - Run this before attempting conversion
import os
import shutil
import psutil

def check_system_requirements(input_path, output_dir):
    """Check if system has enough resources for the conversion"""
    
    print("=== SYSTEM REQUIREMENTS CHECK ===")
    
    # File size
    if os.path.exists(input_path):
        file_size_gb = os.path.getsize(input_path) / (1024**3)
        print(f"Input file size: {file_size_gb:.1f} GB")
    else:
        print(f"WARNING: Input file not found: {input_path}")
        return False
    
    # Available memory
    memory = psutil.virtual_memory()
    available_memory_gb = memory.available / (1024**3)
    total_memory_gb = memory.total / (1024**3)
    print(f"Available RAM: {available_memory_gb:.1f} GB / {total_memory_gb:.1f} GB")
    
    # Available disk space
    disk_usage = shutil.disk_usage(output_dir)
    available_disk_gb = disk_usage.free / (1024**3)
    print(f"Available disk space: {available_disk_gb:.1f} GB")
    
    # Recommendations
    print("\n=== RECOMMENDATIONS ===")
    
    # Memory recommendation
    if available_memory_gb < file_size_gb * 0.1:  # Less than 10% of file size
        print("⚠️  WARNING: Very low available memory!")
        print("   Recommended: Use the chunked processing approach")
        print("   Set chunk_size_mb to 200-500 MB")
    elif available_memory_gb < file_size_gb * 0.3:  # Less than 30% of file size
        print("⚠️  CAUTION: Limited memory available")
        print("   Recommended: Use memory-optimized DuckDB settings")
        print("   Monitor memory usage during conversion")
    else:
        print("✅ Memory should be sufficient for DuckDB conversion")
    
    # Disk space recommendation
    estimated_parquet_size = file_size_gb * 0.3  # Rough estimate: 30% of original size
    if available_disk_gb < estimated_parquet_size * 3:  # Need 3x for temp files
        print("⚠️  WARNING: May not have enough disk space!")
        print(f"   Estimated output size: {estimated_parquet_size:.1f} GB")
        print(f"   Recommended free space: {estimated_parquet_size * 3:.1f} GB")
    else:
        print("✅ Disk space should be sufficient")
    
    print(f"\n=== SUGGESTED APPROACH ===")
    if available_memory_gb >= file_size_gb * 0.3:
        print("1. Try the memory-optimized DuckDB approach first (Cell 15)")
        print("2. If it fails, use the chunked approach (Cell 16)")
    else:
        print("1. Use the chunked processing approach (Cell 16)")
        print("2. Start with chunk_size_mb=200 and increase if stable")
    
    return True

# Run the check
input_path = '<path_to_string_data>/protein.links.detailed.v12.0.txt.gz'
output_dir = '<path_to_string_data>/parquet_output_duckdb'
check_system_requirements(input_path, output_dir)

=== SYSTEM REQUIREMENTS CHECK ===
Input file size: 189.6 GB
Available RAM: 120.1 GB / 125.6 GB
Available disk space: 189.2 GB

=== RECOMMENDATIONS ===
✅ Memory should be sufficient for DuckDB conversion
✅ Disk space should be sufficient

=== SUGGESTED APPROACH ===
1. Try the memory-optimized DuckDB approach first (Cell 15)
2. If it fails, use the chunked approach (Cell 16)

True

Filter string data to only include rows with confidence >70% and which are related to a cafa5 protein

Takes ~15 minutues with 64 cpus and slow SLURM disk performance, for faster performance copy protein_links_space_delimited.parquet to SLURM_TEMPDIR with above cell

In [13]:
import polars as pl

input_parquet_path = (
    STRING_PROTEIN_LINKS_PARQUET
)

# Configuration: use all threads and a suitable streaming chunk size
pl.Config.set_streaming_chunk_size(1_000_000)  # Optional: tune chunk size for streaming

MIN_COMBINED_SCORE = 700

# Build swissprot ID list (assuming swissprot_pl is a Polars DataFrame already in memory)
string_ids = swissprot_pl["string_id"].drop_nulls().unique().to_list()
print(f"swissprot filter will use {len(string_ids)} unique string IDs")

# Lazy scan with optimized parallelism
lf = pl.scan_parquet(
    input_parquet_path,
    parallel="row_groups",   # parallelize over row groups to utilize all cores
    use_statistics=True      # enable Parquet page skipping by stats
    # low_memory=False is default (we prefer performance),
    # rechunk=False is default (avoid extra copying before collect)
)

# Apply filters lazily
lf = lf.filter(pl.col("combined_score") >= MIN_COMBINED_SCORE)
lf = lf.filter(pl.col("protein1").is_in(string_ids))

# Collect results with streaming (to pipeline reading & filtering)
print("Executing query in streaming mode...")
final_df = lf.collect(engine="streaming")  # or engine="streaming" on newer Polars

print("Done! Final dataframe has shape", final_df.shape)

swissprot filter will use 208429 unique string IDs
Executing query in streaming mode...

:

In [7]:
# FIXED VERSION: Use the existing code with polars-u64-idx
# Run this after installing polars-u64-idx and restarting kernel

import polars as pl

input_parquet_path = (
    STRING_PROTEIN_LINKS_PARQUET
)

# Check if we have the large-dataset version of polars
try:
    # Test if polars supports large datasets
    print("Polars version:", pl.__version__)
    print("Checking polars build configuration...")
    
    # This will help identify if we have the right version
    dummy_large_range = range(2**33)  # Larger than 2^32
    print("✅ Python can handle large ranges")
    
except Exception as e:
    print(f"⚠️  Issue detected: {e}")

# Configuration: use conservative settings for large datasets
pl.Config.set_streaming_chunk_size(500_000)  # Smaller chunks for stability

MIN_COMBINED_SCORE = 700

# Build swissprot ID list
string_ids = swissprot_pl["string_id"].drop_nulls().unique().to_list()
print(f"swissprot filter will use {len(string_ids)} unique string IDs")

# Use more conservative approach for large datasets
print("Setting up lazy frame with conservative settings...")

lf = pl.scan_parquet(
    input_parquet_path,
    parallel="columns",      # Use column parallelism instead of row_groups for better memory usage
    use_statistics=True,     # Enable statistics-based filtering
    low_memory=True          # Use less memory during processing
)

# Apply filters lazily
print("Applying filters...")
lf = lf.filter(pl.col("combined_score") >= MIN_COMBINED_SCORE)
lf = lf.filter(pl.col("protein1").is_in(string_ids))

# Collect with conservative settings
print("Executing query with streaming engine...")
try:
    final_df = lf.collect(engine="streaming")
    print("✅ Success! Final dataframe has shape", final_df.shape)
except Exception as e:
    print(f"❌ Error: {e}")
    print("Try running the alternative approach in the next cell")

Polars version: 1.32.3
Checking polars build configuration...
✅ Python can handle large ranges
swissprot filter will use 208429 unique string IDs
Setting up lazy frame with conservative settings...
Applying filters...
Executing query with streaming engine...
✅ Success! Final dataframe has shape (6760068, 10)

In [8]:
final_df.head(10)

shape: (10, 10)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ protein1   ┆ protein2   ┆ neighborho ┆ fusion ┆ … ┆ experimen ┆ database ┆ textminin ┆ combined_ │
│ ---        ┆ ---        ┆ od         ┆ ---    ┆   ┆ tal       ┆ ---      ┆ g         ┆ score     │
│ str        ┆ str        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ i64      ┆ ---       ┆ ---       │
│            ┆            ┆ i64        ┆        ┆   ┆ i64       ┆          ┆ i64       ┆ i64       │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 372       ┆ 875       │
│ 4305       ┆ 8805       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 569        ┆ 0      ┆ … ┆ 99        ┆ 952      ┆ 531       ┆ 999       │
│ 4305       ┆ 4310       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 116        ┆ 0      ┆ … ┆ 0         ┆ 435      ┆ 173       ┆ 884       │
│ 4305       ┆ 7380       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 109        ┆ 0      ┆ … ┆ 0         ┆ 907      ┆ 173       ┆ 925       │
│ 4305       ┆ 4080       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 373       ┆ 884       │
│ 4305       ┆ 8800       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 264        ┆ 0      ┆ … ┆ 0         ┆ 484      ┆ 385       ┆ 883       │
│ 4305       ┆ 0825       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 92         ┆ 0      ┆ … ┆ 0         ┆ 952      ┆ 374       ┆ 981       │
│ 4305       ┆ 5665       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 381       ┆ 770       │
│ 4305       ┆ 8815       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 92         ┆ 0      ┆ … ┆ 0         ┆ 952      ┆ 379       ┆ 981       │
│ 4305       ┆ 4765       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 382       ┆ 915       │
│ 4305       ┆ 8820       ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [10]:
print("Estimated in-memory size:", final_df.estimated_size() / 1e6, "MB")

Estimated in-memory size: 644.104237 MB

Writes the filtered string dataframe to disk

In [11]:
output_path = os.path.join(OUTPUT_DIR, "filtered_protein_links.parquet")
final_df.write_parquet(output_path, compression="zstd")

Reads the filtered string dataframe

In [12]:
import polars as pl

# Path to the saved file
output_path = os.path.join(OUTPUT_DIR, "filtered_protein_links.parquet")

# Read the file
filtered_df = pl.read_parquet(output_path)

# Show shape and head
print("Shape:", filtered_df.shape)
print(filtered_df.tail())

Shape: (6760068, 10)
shape: (5, 10)
┌────────────┬────────────┬────────────┬────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ protein1   ┆ protein2   ┆ neighborho ┆ fusion ┆ … ┆ experimen ┆ database ┆ textminin ┆ combined_ │
│ ---        ┆ ---        ┆ od         ┆ ---    ┆   ┆ tal       ┆ ---      ┆ g         ┆ score     │
│ str        ┆ str        ┆ ---        ┆ i64    ┆   ┆ ---       ┆ i64      ┆ ---       ┆ ---       │
│            ┆            ┆ i64        ┆        ┆   ┆ i64       ┆          ┆ i64       ┆ i64       │
╞════════════╪════════════╪════════════╪════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1921421.M4 ┆ 1921421.M4 ┆ 55         ┆ 0      ┆ … ┆ 0         ┆ 800      ┆ 0         ┆ 802       │
│ 93_12200   ┆ 93_06140   ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 900      ┆ 0         ┆ 900       │
│ 93_12200   ┆ 93_14215   ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 67         ┆ 0      ┆ … ┆ 0         ┆ 900      ┆ 61        ┆ 904       │
│ 93_12200   ┆ 93_16565   ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 783        ┆ 0      ┆ … ┆ 0         ┆ 0        ┆ 123       ┆ 980       │
│ 93_12200   ┆ 93_12205   ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 0          ┆ 0      ┆ … ┆ 0         ┆ 900      ┆ 0         ┆ 900       │
│ 93_12200   ┆ 93_14960   ┆            ┆        ┆   ┆           ┆          ┆           ┆           │
└────────────┴────────────┴────────────┴────────┴───┴───────────┴──────────┴───────────┴───────────┘

replace protein2 string code with protein2 name

In [13]:
import polars as pl

# --- Replace protein2 IDs with their preferred names ---
# 1. Rename original protein2 to protein2_string
filtered_df = filtered_df.rename({"protein2": "protein2_string"})

# 2. Join to bring in the preferred_name from protein_info_df
filtered_df = filtered_df.join(
    protein_info_df.select(["string_protein_id", "preferred_name"]),
    left_on="protein2_string",
    right_on="string_protein_id",
    how="left"
)

# 3. Overwrite protein2 with the joined preferred_name
filtered_df = filtered_df.with_columns(
    pl.col("preferred_name").alias("protein2")
)

# 4. Drop any helper columns that were added
to_drop = [c for c in ["string_protein_id", "preferred_name"] if c in filtered_df.columns]
filtered_df = filtered_df.drop(to_drop)

# Now filtered_df.protein2 contains the preferred names,
# and the original IDs are in filtered_df.protein2_string.

In [14]:
filtered_df

shape: (6_760_068, 11)
┌────────────┬────────────┬────────────┬────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ protein1   ┆ protein2_s ┆ neighborho ┆ fusion ┆ … ┆ database ┆ textminin ┆ combined_ ┆ protein2  │
│ ---        ┆ tring      ┆ od         ┆ ---    ┆   ┆ ---      ┆ g         ┆ score     ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ i64    ┆   ┆ i64      ┆ ---       ┆ ---       ┆ str       │
│            ┆ str        ┆ i64        ┆        ┆   ┆          ┆ i64       ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0        ┆ 372       ┆ 875       ┆ OEG74489. │
│ 4305       ┆ 8805       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 569        ┆ 0      ┆ … ┆ 952      ┆ 531       ┆ 999       ┆ OEG72217. │
│ 4305       ┆ 4310       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 116        ┆ 0      ┆ … ┆ 435      ┆ 173       ┆ 884       ┆ OEG75425. │
│ 4305       ┆ 7380       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 23.BEL05_0 ┆ 23.BEL05_0 ┆ 109        ┆ 0      ┆ … ┆ 907      ┆ 173       ┆ 925       ┆ hisC      │
│ 4305       ┆ 4080       ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 23.BEL05_0 ┆ 23.BEL05_1 ┆ 116        ┆ 0      ┆ … ┆ 0        ┆ 373       ┆ 884       ┆ OEG74488. │
│ 4305       ┆ 8800       ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ …          ┆ …          ┆ …          ┆ …      ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 1921421.M4 ┆ 1921421.M4 ┆ 55         ┆ 0      ┆ … ┆ 800      ┆ 0         ┆ 802       ┆ sucC      │
│ 93_12200   ┆ 93_06140   ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 0          ┆ 0      ┆ … ┆ 900      ┆ 0         ┆ 900       ┆ accA      │
│ 93_12200   ┆ 93_14215   ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 67         ┆ 0      ┆ … ┆ 900      ┆ 61        ┆ 904       ┆ AGT33525. │
│ 93_12200   ┆ 93_16565   ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
│ 1921421.M4 ┆ 1921421.M4 ┆ 783        ┆ 0      ┆ … ┆ 0        ┆ 123       ┆ 980       ┆ nahL      │
│ 93_12200   ┆ 93_12205   ┆            ┆        ┆   ┆          ┆           ┆           ┆           │
│ 1921421.M4 ┆ 1921421.M4 ┆ 0          ┆ 0      ┆ … ┆ 900      ┆ 0         ┆ 900       ┆ AGT33229. │
│ 93_12200   ┆ 93_14960   ┆            ┆        ┆   ┆          ┆           ┆           ┆ 1         │
└────────────┴────────────┴────────────┴────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [15]:
print("swissprot column types:")
print(swissprot_pl.schema)

print("\nFiltered DF column types:")
print(filtered_df.schema)

swissprot column types:
Schema([('protein_id', String), ('protein_names', String), ('protein_function', String), ('organism', String), ('length', Int64), ('subcellular_location', String), ('sequence', String), ('go_ids', List(String)), ('go_bp', List(String)), ('go_mf', List(String)), ('go_cc', List(String)), ('structure_path', String), ('interpro_ids', List(String)), ('interpro_location', String), ('string_id', String)])

Filtered DF column types:
Schema([('protein1', String), ('protein2_string', String), ('neighborhood', Int64), ('fusion', Int64), ('cooccurence', Int64), ('coexpression', Int64), ('experimental', Int64), ('database', Int64), ('textmining', Int64), ('combined_score', Int64), ('protein2', String)])

Groups filtered string df by protein 1 and then adds column with all associated protein 2 and another with all proteins 2 along with individual scores

In [16]:
import polars as pl

grouped_df = (
    filtered_df
    .group_by("protein1")
    .agg([
        # 1. List of all protein2 values per protein1
        pl.col("protein2").implode().alias("interaction_partners"),

        # 2. Struct of full interaction info, collected into list
        pl.struct([
            pl.col("protein2"),
            pl.col("neighborhood"),
            pl.col("fusion"),
            pl.col("cooccurence"),
            pl.col("coexpression"),
            pl.col("experimental"),
            pl.col("database"),
            pl.col("textmining"),
            pl.col("combined_score"),
        ]).implode().alias("full_interaction_info"),
    ])
)

print("Grouped shape:", grouped_df.shape)
print(grouped_df.head())

Grouped shape: (196977, 3)
shape: (5, 3)
┌────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ protein1           ┆ interaction_partners            ┆ full_interaction_info           │
│ ---                ┆ ---                             ┆ ---                             │
│ str                ┆ list[str]                       ┆ list[struct[9]]                 │
╞════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 272844.PAB1184     ┆ ["PAB1179", "atpE", … "atpB"]   ┆ [{"PAB1179",794,0,0,157,498,90… │
│ 315749.Bcer98_0297 ┆ ["gatB", "aspS", … "rpsZ"]      ┆ [{"gatB",743,0,713,732,860,900… │
│ 259536.Psyc_0390   ┆ ["rsfS"]                        ┆ [{"rsfS",109,0,160,752,0,0,106… │
│ 74546.PMT9312_0519 ┆ ["ABB49456.1", "ABB49785.1", …… ┆ [{"ABB49456.1",104,0,0,0,0,900… │
│ 167546.P9301_08341 ┆ ["ABO17458.1", "panB", … "eda"… ┆ [{"ABO17458.1",774,0,0,0,0,0,0… │
└────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [18]:
swissprot_pl

shape: (419_049, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ structure ┆ interpro_ ┆ interpro_ ┆ string_i │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ _path     ┆ ids       ┆ location  ┆ d        │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ list[str] ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q8CX00    ┆ Chaperoni ┆ Together  ┆ Streptoco ┆ … ┆ AF-Q8CX00 ┆ ["IPR0183 ┆ {"IPR0274 ┆ 208435.S │
│           ┆ n GroEL   ┆ with its  ┆ ccus agal ┆   ┆ -F1-model ┆ 70", "IPR ┆ 13": [5,  ┆ AG2074   │
│           ┆           ┆ co-chaper ┆ actiae    ┆   ┆ _v4.cif   ┆ 001844",  ┆ 519],     ┆          │
│           ┆           ┆ oni…      ┆ serot…    ┆   ┆           ┆ … "…      ┆ "IPR02…   ┆          │
│ Q4P9K9    ┆ Chitin    ┆ Polymeriz ┆ Ustilago  ┆ … ┆ AF-Q4P9K9 ┆ ["IPR0016 ┆ {"IPR0274 ┆ 237631.Q │
│           ┆ synthase  ┆ es        ┆ maydis    ┆   ┆ -F1-model ┆ 09", "IPR ┆ 17": [5,  ┆ 4P9K9    │
│           ┆ 8         ┆ chitin, a ┆ (strain   ┆   ┆ _v4.cif   ┆ 004835",  ┆ 771],     ┆          │
│           ┆           ┆ structur… ┆ 521 / …   ┆   ┆           ┆ … "…      ┆ "IPR03…   ┆          │
│ A9WUW1    ┆ ATP-depen ┆ ATP-depen ┆ Renibacte ┆ … ┆ AF-A9WUW1 ┆ ["IPR0500 ┆ {"IPR0383 ┆ 288705.R │
│           ┆ dent Clp  ┆ dent spec ┆ rium salm ┆   ┆ -F1-model ┆ 52", "IPR ┆ 66": [3,  ┆ Sal33209 │
│           ┆ protease  ┆ ificity   ┆ oninarum  ┆   ┆ _v4.cif   ┆ 038366",  ┆ 50],      ┆ _3266    │
│           ┆ ATP…      ┆ comp…     ┆ (st…      ┆   ┆           ┆ … "…      ┆ "IPR027…  ┆          │
│ A0A411KZU ┆ Burnettra ┆ Part of   ┆ Aspergill ┆ … ┆ AF-A0A411 ┆ ["IPR0532 ┆ {"IPR0532 ┆ null     │
│ 9         ┆ mic acids ┆ the gene  ┆ us        ┆   ┆ KZU9-F1-m ┆ 21"]      ┆ 21": [2,  ┆          │
│           ┆ biosynthe ┆ cluster   ┆ burnettii ┆   ┆ odel_v4.c ┆           ┆ 363]}     ┆          │
│           ┆ si…       ┆ that …    ┆           ┆   ┆ if        ┆           ┆           ┆          │
│ Q0AE59    ┆ 50S       ┆ null      ┆ Nitrosomo ┆ … ┆ AF-Q0AE59 ┆ ["IPR0209 ┆ {"IPR0002 ┆ 335283.N │
│           ┆ ribosomal ┆           ┆ nas       ┆   ┆ -F1-model ┆ 39", "IPR ┆ 71": [1,  ┆ eut_2151 │
│           ┆ protein   ┆           ┆ eutropha  ┆   ┆ _v4.cif   ┆ 000271"]  ┆ 44],      ┆          │
│           ┆ L34       ┆           ┆ (strain … ┆   ┆           ┆           ┆ "IPR020…  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Q0C5R4    ┆ 3-phospho ┆ Catalyzes ┆ Hyphomona ┆ … ┆ AF-Q0C5R4 ┆ ["IPR0137 ┆ {"IPR0137 ┆ 228405.H │
│           ┆ shikimate ┆ the       ┆ s         ┆   ┆ -F1-model ┆ 92", "IPR ┆ 92": [5,  ┆ NE_0195  │
│           ┆ 1-carboxy ┆ transfer  ┆ neptunium ┆   ┆ _v4.cif   ┆ 006264",  ┆ 436],     ┆          │
│           ┆ vi…       ┆ of the …  ┆ (strain   ┆   ┆           ┆ … "…      ┆ "IPR03…   ┆          │
│           ┆           ┆           ┆ A…        ┆   ┆           ┆           ┆           ┆          │
│ P0A6S8    ┆ Glycerol- ┆ null      ┆ Escherich ┆ … ┆ AF-P0A6S8 ┆ ["IPR0362 ┆ {"IPR0362 ┆ 199310.c │
│           ┆ 3-phospha ┆           ┆ ia coli   ┆   ┆ -F1-model ┆ 91", "IPR ┆ 91": [8,  ┆ 4430     │
│           ┆ te dehydr ┆           ┆ O6:H1     ┆   ┆ _v4.cif   ┆ 013328",  ┆ 182],     ┆          │
│           ┆ oge…      ┆           ┆ (strain…  ┆   ┆           ┆ … "…      ┆ "IPR00…   ┆          │
│ B7NN18    ┆ Periplasm ┆ Catalytic ┆ Escherich ┆ … ┆ AF-B7NN18 ┆ ["IPR0066 ┆ {"IPR0090 ┆ 585057.E │
│           ┆ ic        ┆ subunit   ┆ ia coli   ┆   ┆ -F1-model ┆ 56", "IPR ┆ 10":      ┆ CIAI39_2 │
│           ┆ nitrate   ┆ of the    ┆ O7:K1     ┆   ┆ _v4.cif   ┆ 006657",  ┆ [688,     ┆ 344      │
│           ┆ reductase ┆ perip…    ┆ (strain…  ┆   ┆           ┆ … "…      ┆ 828],     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ "IPR…     ┆          │
│ A9KE87    ┆ tRNA-spec ┆ Catalyzes ┆ Coxiella  ┆ … ┆ AF-A9KE87 ┆ ["IPR0468 ┆ {"IPR0147 ┆ null     │
│           ┆ ific 2-th ┆ the 2-thi ┆ burnetii  ┆   ┆ -F1-model ┆ 85", "IPR ┆ 29": [1,  ┆          │
│           ┆ iouridyla ┆ olation   ┆ (strain   ┆   ┆ _v4.cif   ┆ 014729",  ┆ 213],     ┆          │
│           ┆ se …      ┆ of …      ┆ Dugw…     ┆   ┆           ┆ … "…      ┆ "IPR02…   ┆          │
│ Q9TDN0    ┆ Cytochrom ┆ Component ┆ Peponocep ┆ … ┆ AF-Q9TDN0 ┆ ["IPR0161 ┆ {"IPR0161 ┆ null     │
│           ┆ e b       ┆ of the    ┆ hala      ┆   ┆ -F1-model ┆ 74", "IPR ┆ 74": [1,  ┆          │
│           ┆           ┆ ubiquinol ┆ electra   ┆   ┆ _v4.cif   ┆ 005797",  ┆ 260],     ┆          │
│           ┆           ┆ -cyt…     ┆           ┆   ┆           ┆ … "…      ┆ "IPR02…   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Connects the PPI data with the cafa5 data

In [19]:
merged_df = swissprot_pl.join(
    grouped_df,
    left_on="string_id",
    right_on="protein1",
    how="left"
)

# Only drop 'protein1' if it exists (e.g., when join didn't auto-drop it)
if "protein1" in merged_df.columns:
    merged_df = merged_df.drop("protein1")

print("Merged shape:", merged_df.shape)
print(merged_df.select(["string_id", "interaction_partners", "full_interaction_info"]).head())

Merged shape: (419049, 17)
shape: (5, 3)
┌───────────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ string_id             ┆ interaction_partners            ┆ full_interaction_info           │
│ ---                   ┆ ---                             ┆ ---                             │
│ str                   ┆ list[str]                       ┆ list[struct[9]]                 │
╞═══════════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 208435.SAG2074        ┆ ["groES", "dnaJ", … "fusA"]     ┆ [{"groES",588,0,294,924,999,0,… │
│ 237631.Q4P9K9         ┆ ["UMAG_11497"]                  ┆ [{"UMAG_11497",0,0,0,103,0,912… │
│ 288705.RSal33209_3266 ┆ ["atpD", "clpP.3", … "dnaK"]    ┆ [{"atpD",0,814,0,0,0,0,246,854… │
│ null                  ┆ null                            ┆ null                            │
│ 335283.Neut_2151      ┆ ["Neut_1653", "nusA", … "rplS"… ┆ [{"Neut_1653",0,0,0,107,809,0,… │
└───────────────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [22]:
# The percentage of rows in swissprot WITHOUT an entry in string->uniprot table
sum(merged_df['string_id'].is_null())

210620

In [23]:
# The percent of rows in swissprot WITHOUT interaction partners
sum(merged_df['interaction_partners'].is_null())/len(merged_df)*100

52.99427990521395

Saves the cafa5 data with the 2 new PPI columns to disk

In [24]:
output_path = os.path.join(OUTPUT_DIR, "swissprot_merged_with_interactions.parquet")

merged_df.write_parquet(output_path, compression="zstd")

In [25]:
import polars as pl

# Path to the saved file
merged_path = os.path.join(OUTPUT_DIR, "swissprot_merged_with_interactions.parquet")

# Read the merged DataFrame
merged_df = pl.read_parquet(merged_path)

# Preview shape and a few rows
print("Shape:", merged_df.shape)
merged_df.sample(9)

Shape: (419049, 17)

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ interpro_ ┆ string_id ┆ interacti ┆ full_int │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ location  ┆ ---       ┆ on_partne ┆ eraction │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str       ┆ rs        ┆ _info    │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ list[str] ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ uct[9]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Q31YW2    ┆ S-formylg ┆ Serine    ┆ Shigella  ┆ … ┆ {"IPR0290 ┆ null      ┆ null      ┆ null     │
│           ┆ lutathion ┆ hydrolase ┆ boydii    ┆   ┆ 58": [1,  ┆           ┆           ┆          │
│           ┆ e         ┆ involved  ┆ serotype  ┆   ┆ 277],     ┆           ┆           ┆          │
│           ┆ hydrolase ┆ in t…     ┆ 4 (st…    ┆   ┆ "IPR01…   ┆           ┆           ┆          │
│           ┆ …         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q8TZB2    ┆ 50S       ┆ null      ┆ Methanopy ┆ … ┆ {"IPR0385 ┆ 190192.MK ┆ ["MK1619" ┆ [{"MK161 │
│           ┆ ribosomal ┆           ┆ rus       ┆   ┆ 62": [32, ┆ 0023      ┆ ,         ┆ 9",0,0,1 │
│           ┆ protein   ┆           ┆ kandleri  ┆   ┆ 96],      ┆           ┆ "MK0125", ┆ 52,772,0 │
│           ┆ L34e      ┆           ┆ (strain … ┆   ┆ "IPR04…   ┆           ┆ … "rpsG"] ┆ ,0,0,7…  │
│ Q8D209    ┆ 50S       ┆ One of    ┆ Wiggleswo ┆ … ┆ {"IPR0123 ┆ 36870.gen ┆ ["rpsP",  ┆ [{"rpsP" │
│           ┆ ribosomal ┆ the       ┆ rthia glo ┆   ┆ 40": [1,  ┆ e:1036905 ┆ "yidC", … ┆ ,0,0,0,9 │
│           ┆ protein   ┆ primary   ┆ ssinidia  ┆   ┆ 125],     ┆ 5         ┆ "rpmE"]   ┆ 39,910,0 │
│           ┆ L2        ┆ rRNA      ┆ bre…      ┆   ┆ "IPR01…   ┆           ┆           ┆ ,412,9…  │
│           ┆           ┆ bindin…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ P37352    ┆ Homoproto ┆ Decarboxy ┆ Escherich ┆ … ┆ {"IPR0366 ┆ null      ┆ null      ┆ null     │
│           ┆ catechuat ┆ lates     ┆ ia coli   ┆   ┆ 63": [1,  ┆           ┆           ┆          │
│           ┆ e catabol ┆ OPET (5-o ┆           ┆   ┆ 427],     ┆           ┆           ┆          │
│           ┆ ism…      ┆ xo-pen…   ┆           ┆   ┆ "IPR01…   ┆           ┆           ┆          │
│ O21872    ┆ Probable  ┆ Forms the ┆ Lactococc ┆ … ┆ NaN       ┆ null      ┆ null      ┆ null     │
│           ┆ portal    ┆ portal    ┆ us phage  ┆   ┆           ┆           ┆           ┆          │
│           ┆ protein   ┆ vertex of ┆ SK1       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ the…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q1RC21    ┆ tRNA-cyti ┆ Catalyzes ┆ Escherich ┆ … ┆ {"IPR0147 ┆ null      ┆ null      ┆ null     │
│           ┆ dine(32)  ┆ the ATP-d ┆ ia coli   ┆   ┆ 29": [2,  ┆           ┆           ┆          │
│           ┆ 2-sulfurt ┆ ependent  ┆ (strain   ┆   ┆ 264],     ┆           ┆           ┆          │
│           ┆ ran…      ┆ 2-…       ┆ UTI89…    ┆   ┆ "IPR03…   ┆           ┆           ┆          │
│ P44048    ┆ Probable  ┆ Could be  ┆ Haemophil ┆ … ┆ {"IPR0367 ┆ 71421.HI_ ┆ ["mltC",  ┆ [{"mltC" │
│           ┆ Fe(2+)-tr ┆ a         ┆ us influe ┆   ┆ 66": [1,  ┆ 0760      ┆ "mutY"]   ┆ ,760,0,0 │
│           ┆ afficking ┆ mediator  ┆ nzae      ┆   ┆ 90],      ┆           ┆           ┆ ,75,0,0, │
│           ┆ pr…       ┆ in iron   ┆ (strain…  ┆   ┆ "IPR007…  ┆           ┆           ┆ 0,768}…  │
│           ┆           ┆ tr…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q0CRX0    ┆ Tyrosinas ┆ Tyrosinas ┆ Aspergill ┆ … ┆ {"IPR0089 ┆ 341663.Q0 ┆ ["ATEG_04 ┆ [{"ATEG_ │
│           ┆ e P       ┆ e; part   ┆ us        ┆   ┆ 22": [11, ┆ CRX0      ┆ 402", "AT ┆ 04402",0 │
│           ┆           ┆ of the    ┆ terreus   ┆   ┆ 356],     ┆           ┆ EG_10366" ┆ ,0,0,0,5 │
│           ┆           ┆ gene c…   ┆ (strain   ┆   ┆ "IPR0…    ┆           ┆ , ……      ┆ 9,830,…  │
│           ┆           ┆           ┆ NI…       ┆   ┆           ┆           ┆           ┆          │
│ A5FZW0    ┆ 50S       ┆ This      ┆ Acidiphil ┆ … ┆ {"IPR0363 ┆ 349163.Ac ┆ ["rplC",  ┆ [{"rplC" │
│           ┆ ribosomal ┆ protein   ┆ ium       ┆   ┆ 94": [10, ┆ ry_1941   ┆ "thrS", … ┆ ,798,0,3 │
│           ┆ protein   ┆ binds spe ┆ cryptum   ┆   ┆ 145],     ┆           ┆ "Acry_181 ┆ 85,866,8 │
│           ┆ L22       ┆ cificall… ┆ (strain   ┆   ┆ "IPR0…    ┆           ┆ 6"…       ┆ 48,700…  │
│           ┆           ┆           ┆ J…        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
merged_df.sample(10)

shape: (10, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein_i ┆ protein_n ┆ protein_f ┆ organism  ┆ … ┆ interpro_ ┆ string_id ┆ interacti ┆ full_int │
│ d         ┆ ames      ┆ unction   ┆ ---       ┆   ┆ location  ┆ ---       ┆ on_partne ┆ eraction │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str       ┆ rs        ┆ _info    │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ list[str] ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ uct[9]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ A0LDW8    ┆ ATP       ┆ F(1)F(0)  ┆ Magnetoco ┆ … ┆ {"IPR0500 ┆ 156889.Mm ┆ ["rplW",  ┆ [{"rplW" │
│           ┆ synthase  ┆ ATP       ┆ ccus      ┆   ┆ 59": [20, ┆ c1_3676   ┆ "rpoA", … ┆ ,0,0,0,8 │
│           ┆ subunit b ┆ synthase  ┆ marinus   ┆   ┆ 180],     ┆           ┆ "atpC"]   ┆ 46,0,0,1 │
│           ┆           ┆ produces… ┆ (strain … ┆   ┆ "IPR0…    ┆           ┆           ┆ 41,862…  │
│ A9L5P8    ┆ 50S       ┆ This      ┆ Shewanell ┆ … ┆ {"IPR0089 ┆ null      ┆ null      ┆ null     │
│           ┆ ribosomal ┆ protein   ┆ a baltica ┆   ┆ 91": [1,  ┆           ┆           ┆          │
│           ┆ protein   ┆ is        ┆ (strain   ┆   ┆ 114],     ┆           ┆           ┆          │
│           ┆ L19       ┆ located   ┆ OS1…      ┆   ┆ "IPR03…   ┆           ┆           ┆          │
│           ┆           ┆ at the…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ Q5M1X5    ┆ 30S       ┆ null      ┆ Streptoco ┆ … ┆ {"IPR0235 ┆ null      ┆ null      ┆ null     │
│           ┆ ribosomal ┆           ┆ ccus ther ┆   ┆ 91": [6,  ┆           ┆           ┆          │
│           ┆ protein   ┆           ┆ mophilus  ┆   ┆ 230],     ┆           ┆           ┆          │
│           ┆ S2        ┆           ┆ (st…      ┆   ┆ "IPR00…   ┆           ┆           ┆          │
│ B5XRE3    ┆ DNA repli ┆ Trans-act ┆ Klebsiell ┆ … ┆ {"IPR0363 ┆ null      ┆ null      ┆ null     │
│           ┆ cation    ┆ ing       ┆ a pneumon ┆   ┆ 84": [5,  ┆           ┆           ┆          │
│           ┆ terminus  ┆ protein   ┆ iae       ┆   ┆ 307],     ┆           ┆           ┆          │
│           ┆ site-…    ┆ required  ┆ (strain … ┆   ┆ "IPR03…   ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ B9DSW1    ┆ 50S       ┆ One of    ┆ Streptoco ┆ … ┆ {"IPR0147 ┆ 218495.SU ┆ ["rpsN",  ┆ [{"rpsN" │
│           ┆ ribosomal ┆ two       ┆ ccus      ┆   ┆ 22": [1,  ┆ B0079     ┆ "rpsL", … ┆ ,702,0,0 │
│           ┆ protein   ┆ assembly  ┆ uberis    ┆   ┆ 99],      ┆           ┆ "ffh"]    ┆ ,601,642 │
│           ┆ L24       ┆ initiator ┆ (strain   ┆   ┆ "IPR008…  ┆           ┆           ┆ ,81,17…  │
│           ┆           ┆ …         ┆ A…        ┆   ┆           ┆           ┆           ┆          │
│ Q5HQ36    ┆ Phenylala ┆ null      ┆ Staphyloc ┆ … ┆ {"IPR0458 ┆ 176279.SE ┆ ["tyrS",  ┆ [{"tyrS" │
│           ┆ nine--tRN ┆           ┆ occus epi ┆   ┆ 64": [10, ┆ RP0721    ┆ "pheT", … ┆ ,109,0,0 │
│           ┆ A ligase  ┆           ┆ dermidis  ┆   ┆ 346],     ┆           ┆ "fusA"]   ┆ ,447,0,0 │
│           ┆ alp…      ┆           ┆ (st…      ┆   ┆ "IPR0…    ┆           ┆           ┆ ,456,7…  │
│ A4Y564    ┆ Probable  ┆ null      ┆ Shewanell ┆ … ┆ {"IPR0161 ┆ 319224.Sp ┆ ["hisI"]  ┆ [{"hisI" │
│           ┆ phosphata ┆           ┆ a putrefa ┆   ┆ 95": [5,  ┆ utcn32_13 ┆           ┆ ,201,0,0 │
│           ┆ se Sputcn ┆           ┆ ciens     ┆   ┆ 241],     ┆ 69        ┆           ┆ ,572,0,0 │
│           ┆ 32_…      ┆           ┆ (strai…   ┆   ┆ "IPR02…   ┆           ┆           ┆ ,436,7…  │
│ P18377    ┆ Virion    ┆ DNA       ┆ Vaccinia  ┆ … ┆ {"IPR0508 ┆ null      ┆ null      ┆ null     │
│           ┆ nicking-j ┆ nicking   ┆ virus     ┆   ┆ 74": [8,  ┆           ┆           ┆          │
│           ┆ oining    ┆ enzyme    ┆ (strain   ┆   ┆ 392],     ┆           ┆           ┆          │
│           ┆ enzyme    ┆ that      ┆ Western…  ┆   ┆ "IPR00…   ┆           ┆           ┆          │
│           ┆           ┆ cleave…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ A9KXA9    ┆ FMN-depen ┆ Quinone   ┆ Shewanell ┆ … ┆ {"IPR0290 ┆ null      ┆ null      ┆ null     │
│           ┆ dent NADH ┆ reductase ┆ a baltica ┆   ┆ 39": [1,  ┆           ┆           ┆          │
│           ┆ :quinone  ┆ that      ┆ (strain   ┆   ┆ 198],     ┆           ┆           ┆          │
│           ┆ oxi…      ┆ provide…  ┆ OS1…      ┆   ┆ "IPR05…   ┆           ┆           ┆          │
│ B5Z2K4    ┆ L-ribulos ┆ Catalyzes ┆ Escherich ┆ … ┆ {"IPR0364 ┆ null      ┆ null      ┆ null     │
│           ┆ e-5-phosp ┆ the isome ┆ ia coli   ┆   ┆ 09": [1,  ┆           ┆           ┆          │
│           ┆ hate      ┆ rization  ┆ O157:H7   ┆   ┆ 227],     ┆           ┆           ┆          │
│           ┆ 4-epime…  ┆ of…       ┆ (stra…    ┆   ┆ "IPR02…   ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
from datasets import Dataset
import polars as pl

# Extract protein IDs from existing train and test DataFrames
train_protein_ids = train_pl["protein_id"].unique().to_list()
test_protein_ids = test_pl["protein_id"].unique().to_list()

print(f"Train set has {len(train_protein_ids)} unique protein IDs")
print(f"Test set has {len(test_protein_ids)} unique protein IDs")

# Check for any overlap between train and test (should be none)
overlap = set(train_protein_ids) & set(test_protein_ids)
if overlap:
    print(f"⚠️  WARNING: Found {len(overlap)} overlapping protein IDs between train and test")
else:
    print("✅ No overlap between train and test protein IDs")

# Split merged_df using protein_id matching
train_merged = merged_df.filter(pl.col("protein_id").is_in(train_protein_ids))
test_merged = merged_df.filter(pl.col("protein_id").is_in(test_protein_ids))

print(f"Train merged dataset: {train_merged.shape}")
print(f"Test merged dataset: {test_merged.shape}")
print(f"Total merged dataset: {merged_df.shape}")

# Verify we captured all data
total_split = train_merged.height + test_merged.height
if total_split == merged_df.height:
    print("✅ All data successfully split into train/test")
else:
    missing = merged_df.height - total_split
    print(f"⚠️  {missing} rows not assigned to train or test (possibly due to missing protein IDs)")

# Convert to pandas for HuggingFace Dataset creation
train_pd = train_merged.to_pandas()
test_pd = test_merged.to_pandas()

# Create HuggingFace datasets
train_hf = Dataset.from_pandas(train_pd, preserve_index=False)
test_hf = Dataset.from_pandas(test_pd, preserve_index=False)

print(f"\nHuggingFace datasets created:")
print(f"Train: {len(train_hf)} samples")
print(f"Test: {len(test_hf)} samples")

Train set has 333677 unique protein IDs
Test set has 83420 unique protein IDs
✅ No overlap between train and test protein IDs
Train merged dataset: (335230, 17)
Test merged dataset: (83819, 17)
Total merged dataset: (419049, 17)
✅ All data successfully split into train/test

HuggingFace datasets created:
Train: 335230 samples
Test: 83819 samples

In [31]:
train_hf

Dataset({
    features: ['protein_id', 'protein_names', 'protein_function', 'organism', 'length', 'subcellular_location', 'sequence', 'go_ids', 'go_bp', 'go_mf', 'go_cc', 'structure_path', 'interpro_ids', 'interpro_location', 'string_id', 'interaction_partners', 'full_interaction_info'],
    num_rows: 335230
})

In [34]:
# Upload dataset to Hugging Face Hub
# First, login to Hugging Face

from huggingface_hub import login, HfApi
import os

# Login to Hugging Face (this will prompt for your token)
print("Please login to Hugging Face Hub...")
print("You'll need your Hugging Face token (get it from https://huggingface.co/settings/tokens)")

try:
    login()
    print("✅ Successfully logged in to Hugging Face!")
except Exception as e:
    print(f"❌ Login failed: {e}")
    print("Please make sure you have a valid token and try again.")

Please login to Hugging Face Hub...
You'll need your Hugging Face token (get it from https://huggingface.co/settings/tokens)

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

✅ Successfully logged in to Hugging Face!

In [35]:
# Upload the dataset to Hugging Face Hub
# This will create a new dataset repo and upload your data

from datasets import DatasetDict

# Configuration for upload
REPO_NAME = "wanglab/cafa5"  # Change this to your desired repo name
# Alternative: use your username like "yourusername/cafa5_with_ppi"

print(f"Preparing to upload dataset to: {REPO_NAME}")
print("This may take several minutes depending on dataset size...")

# First, create the DatasetDict from your train_hf and test_hf
print("Creating DatasetDict from train and test datasets...")
cafa5_ds = DatasetDict({
    "train": train_hf,
    "test": test_hf,
})

print(f"DatasetDict created with {len(cafa5_ds['train'])} training and {len(cafa5_ds['test'])} test samples")

try:
    # Push the dataset to the Hub with task_name configuration
    print("Uploading to Hugging Face Hub...")
    cafa5_ds.push_to_hub(
        repo_id=REPO_NAME,
        config_name="swissprot_reasoning",  # This sets the task_name/config_name
        private=False,  # Set to True if you want a private dataset
        commit_message="Add CAFA5 dataset with protein-protein interactions from STRING database"
    )
    
    print(f"✅ Successfully uploaded dataset to: https://huggingface.co/datasets/{REPO_NAME}")
    print(f"Dataset contains {len(cafa5_ds['train'])} training samples and {len(cafa5_ds['test'])} test samples")
    print(f"Task name/config: swissprot_reasoning")
    
except Exception as e:
    print(f"❌ Upload failed: {e}")
    print("Common issues:")
    print("1. Make sure you're logged in (run previous cell)")
    print("2. Check if the repository name already exists")
    print("3. Verify you have permission to create datasets under 'wanglab' org")
    print("   - If not, change REPO_NAME to use your username instead")

Preparing to upload dataset to: wanglab/cafa5
This may take several minutes depending on dataset size...
Creating DatasetDict from train and test datasets...
DatasetDict created with 335230 training and 83819 test samples
Uploading to Hugging Face Hub...

Uploading the dataset shards:   0%|          | 0/3 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/112 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

Creating parquet from Arrow format:   0%|          | 0/112 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

Creating parquet from Arrow format:   0%|          | 0/112 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/84 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

README.md: 0.00B [00:00, ?B/s]

✅ Successfully uploaded dataset to: https://huggingface.co/datasets/wanglab/cafa5
Dataset contains 335230 training samples and 83819 test samples
Task name/config: swissprot_reasoning